- .stignore
- deploy/charts/beta9/values.yaml
- internal/abstractions/volume/volume.go
- internal/common/config.default.yaml
- internal/gateway/gateway.go
- internal/proxy/proxy.go
- internal/types/config.go
- internal/worker/worker.go
- manifests/kustomize/components/beta9-gateway/deployment.yaml
- Gateway: Use timeout on http shutdown
- Gateway: Use gracefulstop on grpc shutdown
- Gateway: Call cancel func at the end
- Gateway: Add termination grace period
- Proxy: Add http server for readiness probe
- Proxy: Stop accepting connections during shutdown (via readiness prob failure), but wait for active connections to finish
- Proxy: Add init container for local dev
- Proxy: Add readiness probe for local dev
- Proxy: Add termination grace period
- Proxy: Fix redis client name
- Worker: Collect all errors during shutdown and return them
- Worker: Call cancel func after remove worker from repo
- Worker: Remove calling cancel func again
- Worker: Close channels when Run() completes
Resolve BE-1356
> Improve shutdown and connection termination

- go.mod
- go.sum
- pkg/worker/image.go
- pkg/worker/worker.go
- Save fuse servers in safemap for later cleanup
- Clean up fuse servers by unmounting them when worker shuts down (assume server process may remain useful during lifecycle of the worker)
> Cleanup active fuse mounts

- pkg/abstractions/image/build.go
- pkg/abstractions/image/image.go
- Properly escape dependencies (for example `bitsandbytes<0.1`
- Use correct base image tag
> Escape packages properly, correct base tag

- sdk/src/beta9/cli/container.py
Before:
```
ID        Status   Stub Id   Scheduled At
───────────────────────────────────────────
0 items
```
After
```
No containers found.
```
> Render a better empty container list message

- pkg/common/redis.go
- pkg/common/redis_test.go
- Remove check to see if lock exists and instead rely on redislock retry system + mutex
> Remove map check in redis lock

- pkg/worker/image.go
- Remove image credential provider since we're storing base images in public repos
> Temporarily remove credential provider in worker image client

- sdk/pyproject.toml
- sdk/src/beta9/__main__.py
- Add the ability to run the CLI with `python -m beta9` when beta9 is installed in activated Python environment.
> Allow CLI to be run as a module

- pkg/proxy/proxy.go
- Fix a bug where if tailscale username was not defined, it would render in the proxied hostname
> Conditionally render tailscale username

- pkg/repository/common/paginator.go
This implementation ensures that when retrieving paginated results, an additional result (+1) is included beyond the requested page size. For example, for a page size of 10, the pagination will actually retrieve 11 results. The extra result serves two purposes:
1.	It confirms the presence of a subsequent page.
2.	It provides a starting point for the next page of results.
This pull request ensures that the extra entry is consistently included in the next set of pagination results.
> Paginator Bugfix: Ensure Inclusion of Next Page Indicator in Results

- pkg/abstractions/endpoint/buffer.go
- pkg/abstractions/endpoint/endpoint.go
- pkg/providers/remote_config.go
- Allow endpoints to work through tailscale
- Cache http clients to prevent re-establishing connections
> Proxy tailscale traffic through custom client

- pkg/network/resolve.go
- pkg/types/config.go
- Adds an optional ES output config to types/config.go for use in external providers
- Add dynamic tailscale service resolution func
> Add elasticsearch config for remote config

- bin/setup.sh
- deploy/crusoe/README.md
- deploy/crusoe/config.tf
- deploy/crusoe/main.tf
- deploy/crusoe/variables.tf
- hack/k3d.yaml
- Update Crusoe Terraform provider to the latest to fix Project ID issues
- Update Crusoe deployment README and suffix `terrform-docs` output
- Improve Terraform variable descriptions by mentioning where to get the values from
- Uncomment cloud-init script so that beta9 is downloaded, built, and deployed automatically
- Send all cloud-init script logs to `/var/log/user-data.log` so setup can be observed
- Add kustomize to setup.sh so setup make target can install manifests
- Add port on k3d local setup for internal api development
Resolve BE-1444
> Update Crusoe Cloud single-instance deployment

- pkg/abstractions/endpoint/buffer.go
It turns out, when an http endpoint request is pending, and the request buffer shuts down (if there are no containers running, or the serve is cancelled, etc), we are not returning from this select, and it is locking/unlocking indefinitely. Relevant pprof dump:
```
(pprof) top
Showing nodes accounting for 29.61s, 95.89% of 30.88s total
Dropped 301 nodes (cum <= 0.15s)
Showing top 10 nodes out of 47
flat  flat%   sum%        cum   cum%
9.03s 29.24% 29.24%      9.04s 29.27%  runtime.lock2
7.94s 25.71% 54.95%      7.95s 25.74%  runtime.unlock2
7.62s 24.68% 79.63%     28.65s 92.78%  runtime.selectgo
1.48s  4.79% 84.42%     10.51s 34.03%  runtime.sellock
1.03s  3.34% 87.76%      9.40s 30.44%  runtime.selunlock
0.79s  2.56% 90.32%      0.79s  2.56%  runtime.fastrand (inline)
0.73s  2.36% 92.68% …
```
> Fix high gateway CPU usage

- sdk/pyproject.toml
- sdk/src/beta9/cli/main.py
When using pyapp to build a binary, the --help and --version options output `Usage: python -m beam [OPTIONS] COMMAND [ARGS]... ` and `python -m beam, version 0.2.23` respectively. This fixes that so the `python -m beam` portion is just `beam`.
Resolve BE-1387
> Fix help and version output in CLI

- pkg/providers/remote_config.go
- pkg/scheduler/pool_external.go
- pkg/worker/worker.go
- use external hostname instead of service
- remove tailscale lookup of gateway since it's exposed to internet already
> Fix external tailscale cfg

- sdk/src/beta9/runner/common.py
- sdk/src/beta9/runner/endpoint.py
Gunicorn worker timeout is based off the difference between `current_time` and the `last_modified` time of `tmp` file that belongs to the Worker.
This method here forcefully keeps the worker's post_fork method alive by updating that `tmp` every second
> [Bug] Worker timeout applies to on start function

- pkg/abstractions/container/container.go
- pkg/abstractions/endpoint/endpoint.go
- pkg/abstractions/endpoint/serve.go
- pkg/abstractions/function/function.go
- pkg/abstractions/taskqueue/serve.go
- pkg/abstractions/taskqueue/taskqueue.go
- pkg/common/config.default.yaml
- pkg/gateway/gateway.go
- pkg/gateway/services/service.go
- pkg/gateway/services/stub.go
- pkg/repository/base.go
- pkg/repository/events.go
- pkg/types/backend.go
- pkg/types/config.go
- pkg/types/event.go
HTTP Inputs in Fluent-bit dynamically set `tags` based off the URI of the request.
e.g. a request to `fluentbit.monitoring:9880/tag_name` results in fluent-bit automatically setting a tag of `tag_name` to the event
These tag names are then matched with an output in the example below
```
[OUTPUT]
Name  http
Match tag_name
....
```
By default, the events will map to the tag `http.1` unless it's override in the input. However, I added a mapping that can be set in `config.yaml` to map events to specific tags by event name as such:
```
monitoring:
fluentbit:
events:
mapping:
- name: abstraction.trigger
tag: internal_api
```
> Update events logic to allow mapping specific events to specific tags

- pkg/scheduler/pool_sizing.go
This fixes an edge case with pool sizing where if the default gpu count is set to zero, but free gpu count is set > 0. 
This change ensures if you're resizing a pool with a GPU type set, that you never request workers without any GPUs.
> Don't allow workers to be created with zero gpu count in gpu pools

- sdk/src/beta9/abstractions/base/runner.py
- sdk/src/beta9/abstractions/endpoint.py
- sdk/src/beta9/abstractions/function.py
- sdk/src/beta9/abstractions/taskqueue.py
- sdk/src/beta9/type.py
- Add GPU validation before runner/stub preparation
- Add better type annotations for GpuType and GpuTypeLiteral (strings)
- Add printing of errors when `prepare_runtime` fails on certain validations
- Fix serving a function (ensure not implemented error is printed)
Resolve BE-1500
> Add validations to Runner

- pkg/abstractions/output/output.go
- pkg/api/v1/task.go
- pkg/types/backend.go
- Add a new `output` list to a `task` object that consists of outputs associated with the task
- Generates new public URLs for outputs that expire in 1h
- Reworks some previously private Output service methods to be public
> Add outputs to a task in the task api

- pkg/abstractions/endpoint/http.go
- pkg/abstractions/function/http.go
- pkg/abstractions/taskqueue/http.go
- pkg/repository/backend_postgres.go
- pkg/repository/base.go
- Add support for `/` and `/latest` which points to the latest version of a deployment
- Fix a nil pointer error when not returning an error after GetDeploymentByNameAndVersion() returns one
Resolve BE-1532
> Add latest version endpoints to deployment endpoints

- pkg/storage/juicefs.go
- pkg/worker/worker.go
- If the container instance is not set, the worker would never maintain the worker status and the TTL would expire. This moves the goroutine to directly after the container instance is set in memory.
- Force unmount juicefs (fixes the below error):
```
2024/07/10 19:18:53 Worker exited with error: failed to unmount storage: error executing juicefs umount: exit status 1, output: 2024/07/10 19:18:53.699538 juicefs[117] <FATAL>: fusermount: failed to unmount /data: Device or resource busy [main.go:31]
```
> Fix timing issues in worker

- hack/okteto.yaml
- pkg/abstractions/container/container.go
- pkg/abstractions/endpoint/instance.go
- pkg/api/v1/task.go
- pkg/gateway/services/task.go
- sdk/src/beta9/abstractions/container.py
- sdk/src/beta9/abstractions/endpoint.py
- sdk/src/beta9/runner/common.py
- sdk/src/beta9/runner/container.py
- sdk/src/beta9/runner/endpoint.py
- sdk/src/beta9/runner/function.py
The way we add callbacks is not ideal but currently there are some nuances between abstractions that require task callbacks to be built case by case. 
One of these nuances is how we `end_task` in endpoint. It's location of handling is different than that of task queue, containers, and functions. 
We place `send_callback` after the `end_task` functions.
> Add callback urls to containers and endpoints

- pkg/repository/worker_redis.go
- When not locking, use a redis pipeline to retrieve workers to avoid many synchronous HGetAll calls in series
> Pipeline worker gets

- pkg/api/v1/task.go
- pkg/gateway/gateway.go
- pkg/types/backend.go
- Add `stats.queue_depth` to task get and list endpoints
Resolve BE-1487
> Add stats to task API

- pkg/abstractions/image/build.go
- pkg/abstractions/image/build_test.go
- pkg/worker/image.go
- Improve terminology used to describe an image reference (URI)
- Document the regex that parses the image reference
- Add ability to parse digest of image reference
- Add support for repos that have "/" in the name e.g. nvidia/cuda:latest
- Return an error when the skopeo copy command fails
- Add more tests
Resolve BE-1571
> Fix image parsing image ref

- pkg/abstractions/image/build.go
- pkg/abstractions/image/build_test.go
This image still fails for me because the repo name contains dots: `nvcr.io/nim/meta/llama-3.1-8b-instruct:1.1.0`. It can be fixed by updating the regex to: `(?P<Repo>[a-z0-9][-a-z0-9._]+)`
> Allow dots and underscores in repo name

- pkg/scheduler/pool_external.go
- pkg/worker/runc_server.go
- pkg/worker/worker.go
There are issues with multi-worker workloads stemming from shared access to host ports.
1. Remove container assignment of host port 9090 from all pods in external manifest. We don't need a prometheus metrics endpoint since we push metrics
2. Dynamically acquire any free host port for RunCServer. Currently all workers attempt to acquire port 1989
> Reconfigure worker and agent config for multi-worker agents

- pkg/providers/generic.go
- pkg/scheduler/pool_external.go
- pkg/types/config.go
- Adds a generic external provider as a catch-all for provider pools that don't have any available apis
> Add generic provider

- sdk/src/beta9/abstractions/base/runner.py
Small change to use relative path when parsing the module. With this change, it is possible to run functions from parent directories or do deploys from parent directories. 
Before:
```bash
python 01_getting_started/quickstart.py                                                                                                                                                                           
{'sum': 285}
=> Building image 
=> Using cached image 
=> Syncing files 
Added...
=> Files synced 
=> Running function: <quickstart:square> 
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/beta9/runner/common.py", line 150, in _load
target_module = importlib.import_module(module)
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return …
```
> support relative path for module file

- .gitignore
- sdk/src/beta9/abstractions/queue.py
When using the queue remotely, you get the error below. 
```
Exception ignored in: <function SimpleQueue.__del__ at 0x104d55f80>
Traceback (most recent call last):
File "/Users/minzi/Dev/beam/examples/.venv/lib/python3.12/site-packages/beta9/abstractions/queue.py", line 74, in __del__
AttributeError: 'super' object has no attribute '__del__'
```
I dont think the `__del__` method is needed and it causes this problem so I have removed it. There is no `__del__` on the `BaseAbstraction`.
> remove del from queue

- sdk/src/beta9/runner/function.py
- Fixes an edge case if an import fails during the initial instantiation of FunctionHandler
If import failed, then kwargs/args would not be defined, causing the function container to never exit.
> Fix import error in function runner

- sdk/pyproject.toml
- sdk/src/beta9/cli/main.py
This will stop people from getting the first time prompt if CI is set. Currently even if you provide the token you get hit with it.
> dont prompt in CI

- deploy/charts/beta9/templates/_helpers.tpl
- deploy/charts/beta9/templates/secret.yaml
- deploy/charts/beta9/values.local.yaml
- deploy/charts/beta9/values.yaml
- Add new `config` key to helm chart values.yaml file used for configuring Beta9 
- Mount `config` values as a config file in drop-in directory `/etc/beta9.d/`
- Force deployment when values in `config` key change
Resolve BE-1593
> Add support for configuring Beta9 via helm values

- manifests/kustomize/components/postgresql/helm-chart-generator.yaml
The idea is to use this as an event source for cron/scheduled jobs instead of maintaining our own custom logic (i.e. beat).
It should also be supported by [RDS/Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/PostgreSQL_pg_cron.html#PostgreSQL_pg_cron.otherDB), but it might require a little work to set up (@nickpetrovic any thoughts on this?)
NOTE: This required a custom postgres build, based off the bitnami image:
```
FROM bitnami/postgresql:16.1.0-debian-11-r24
USER root
RUN apt-get update \
&& apt-get upgrade -y \
&& apt-get install -y wget gnupg2 lsb-release \
&& echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
&& wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add …
```
> enable pg_cron in local postgres

- Makefile
- pkg/gateway/gateway.go
- pkg/repository/backend_postgres.go
- pkg/repository/base.go
- pkg/repository/events.go
- pkg/types/event.go
I'm looking for opinions on where to push events for these backend transactions. 
Rather than updating in 15 places where `backendRepo.UpdateTask` is called, I currently have the event happen after the database transaction is fulfilled.
Alternative to this, I can write a layer on top of `backendRepo` such as `backendRepoWithEvents` or something similar that wraps functions such as 
- `UpdateTask`
- `CreateTask`
- and other places where we might want events following a database transaction such as `CreateDeployment`
> Add events for task.created and task.updated

- pkg/api/v1/token.go
- pkg/repository/backend_postgres.go
- pkg/repository/base.go
This PR adds support for additional support for tokens to the gateway. It allows us to delete tokens and we will now return the full token object upon creation. This is useful because it allows users to make subsequent requests using the external token ID without needing to fetch or re-fetch the full list of tokens.
> delete tokens and return full token on create

- pkg/api/v1/deployment.go
- pkg/repository/backend_postgres.go
- pkg/repository/base.go
This PR adds a route to the gateway for downloading deployment objects. It uses the stub ID to generate the download path and returns the file at that path. This will allow us to build a download option into the UI so that users can quickly access/verify their deployed code.
> Add deployment download route

- sdk/src/beta9/abstractions/endpoint.py
- sdk/src/beta9/abstractions/taskqueue.py
This change makes it so that serves are terminated immediately on a user interrupt. The current behavior prompts users to ask if they truly want to end the serve. However, regardless of the user's input the session ends. If they chose "n", indicating they wanted the serve to continue, there will still be a container up that they then need to manually stop. 
This change simplifies things and users can easily start a new serve if they closed the old one on accident.
> Do not prompt user when ending serve

- pkg/worker/base_runc_config.json
This PR adds additional mounts to the base runc config so that beam and beta9 are placed in site-packages as well as dist-packages.
> mount beam & beta9 to site-packages as well

- pkg/abstractions/image/base_requirements.txt
- sdk/src/beta9/abstractions/function.py
- Move croniter import to invocation details func to avoid adding a package to base reqs
- Remove typing_extensions to lower complexity with type requirements
Resolve BE-1650
> Move croniter import to invocation function

- pkg/worker/network.go
- Don't use namespaces to determine leftover network interfaces
- Add comments to iptable rules to indicate container ids they are associated with
- Check container state error explicitly
> Improve network cleanup process

- go.mod
- go.sum
- pkg/common/registry.go
- pkg/worker/image.go
- [CLIP] Fall back to remote source if cache file fails
- [Blobcache] Retry reads 3 times
- [Blobcache] Don't try to retrieve content from cache until we have discovered nearby hosts
- [Blobcache] Lock when storing content from source, to prevent duplicate requests going to cache server
- [Worker] Don't check mountpoint, rely on in-memory fuse server to determine if there is a valid mount running
- [Misc.] Clean up image registry types and logs
> Various image / cache fixes

- manifests/kustomize/components/monitoring/fluent-bit.yaml
- pkg/gateway/services/deployment.go
When stopping a deployment, also stop a scheduled job by deleting it.
Match fluent-bit logging settings with production.
Resolve BE-1713
> Ability to stop scheduled jobs

- pkg/abstractions/endpoint/buffer.go
- pkg/abstractions/endpoint/endpoint.go
- pkg/abstractions/function/function.go
- pkg/abstractions/taskqueue/taskqueue.go
- pkg/gateway/services/stub.go
One special condition we need to consider.
Current behavior:
If a request to endpoint is made, and it starts running on a container -> even if you disconnect the client request the task will still run.
However, if a request to endpoint is made but then client disconnects before the task goes inflight, the task will never run because the request's context is canceled before it ever reached he gunicorn server. Therefore a task like this is stuck in PENDING forever (which this PR helps transitions such tasks to expired)
This behavior of the request state is not anything new and is the current behavior in prod.
> Endpoints should at least transition from pending to expires

- pkg/storage/mountpoint.go
- pkg/worker/mount.go
- pkg/worker/worker.go
This PR adds a container log when a mountpoint setup fails. This way users will know if the credentials they provided were invalid. It also removes the temporary directory from the worker in the case of failure and during clean up.
> log when mountpoint fails and cleanup mountpoint dir 

- pkg/worker/mount.go
- pkg/worker/worker.go
This change allows a container to start even if a mountpoint mount failed. This will result in errors that are visible to users and still log the underlying mountpoint error as well.
> run container even if mountpoint fails

- pkg/gateway/services/stub.go
This PR adds a check to `GetOrCreateStub` that ensures that the user has a valid GPU limit if they've requested to create a stub that includes a GPU.
> Check gpu limit before creating stub

- pkg/abstractions/taskqueue/taskqueue.go
Fixes an issue where taskqueues with keepwarm set to zero would fail with an "Unable to End Task" error:
```
Running task <cfa3d4cc-b4c7-4c50-ab13-c80e36b2b019>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/beta9/runner/taskqueue.py", line 307, in process_tasks
result = handler(context, *args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/beta9/runner/common.py", line 168, in __call__
return self.handler(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/beta9/abstractions/taskqueue.py", line 160, in __call__
return self.local(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/beta9/abstractions/taskqueue.py", line 168, in local
return self.func(*args, **kwargs)
TypeError: transcribe() missing 1 required positional …
```
> Fix zero keepwarm taskqueues

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/function.py
If calling a map from inside a another invoked function, there is the possibility to trigger a recursive invocation of the same code (during import). This should hopefully prevent that from happening.
> Prevent infinite map loops

- sdk/src/beta9/channel.py
- sdk/src/beta9/exceptions.py
- sdk/src/beta9/runner/common.py
- sdk/src/beta9/runner/function.py
- sdk/src/beta9/runner/taskqueue.py
Fixes a couple of bugs:
- ThreadPoolExecutors will block indefinitely if cancel is not called on a task - this removes the wait / join at the end. Without this the process could hang indefinitely
- Moves the ThreadPoolExecutor outside of the context, this was preventing exceptions from bubbling up correctly
- Adds retry logic to end task (affects task queue and function runners)
> Handle errors in runner properly

- sdk/pyproject.toml
- sdk/src/beta9/cli/config.py
- sdk/src/beta9/config.py
- Allow using gateway host and port defaults when prompting for config
- Require token when calling config create command (during prompt, not for cli command)
- Print message when user input prompts are invalid
Resolve BE-1752
> Allow using defaults when prompting for config values

- sdk/pyproject.toml
- sdk/src/beta9/cli/config.py
- sdk/src/beta9/cli/extraclick.py
- sdk/src/beta9/config.py
- Fix default gateway host/port value (Get from SDK settings which can be set externally)
- Use better gRPC error messaging happen when building Click service client
- When we get a context and it doesn't exist, prompt for it, but also save it
- When validating the gateway host, mention it might also be unreachable
- Don't prompt for overwriting a config if it is invalid (no host, port, or token is set), just overwrite it
Resolve BE-1752
> Fix default gateway values and improve error handling in SDK

- sdk/src/beta9/runner/function.py
- sdk/src/beta9/runner/taskqueue.py
If a function completes very quickly, it can sometimes raise a `ValueError`, as monitor_task tries to call a stub with a closed channel. This handles the error and also adds an extra log in case other exceptions pop up that we haven't handled properly.
> Fix unexpected task monitor exception

- pkg/repository/backend_postgres.go
- pkg/types/backend.go
This PR adds deployment information to the task with related query. The query will now return the deployment name, version, and external ID. This can be used to link tasks to their deployment in the UI.
> Add deployment info to task with related query

- pkg/abstractions/output/output.go
- pkg/abstractions/volume/volume.go
Fixes an issue where an output may not be written to disk. This applies the same change to volume uploads.
Resolve BE-1692
> Flush output and volume data to disk on completion

- pkg/api/v1/deployment.go
- pkg/api/v1/task.go
- pkg/gateway/services/stub.go
- pkg/types/backend.go
- Remove (encrypted) secret values from deployment responses
- Move sanitize stub function from task to stub struct
- Update task response function calls to sanitize values; this means secrets come back in the task response, but the values are not returned.
- Add created and updated at dates to stub config of secret so they have valid dates in the frontend
- Remove "empty" attributes of secret type for workspace id and last updated by (both are private ids)
Resolve BE-1799
> Sanitize secret's values

- pkg/abstractions/endpoint/autoscaler.go
- pkg/abstractions/endpoint/serve.go
Currently, if you stop a container that is part of a serve with 
```
beta9 container stop CONTAINER_ID
```
the container will just be scaled back up. It will eventually go away after the TTL expires. It should go away when it is told to. 
With this change, we check to see if the TTL has been recently reset before scaling the container back up. During serves, TTL is reset every time the user syncs new changes. So, if the TTL is stale when the container has gone down, we will assume the container is really meant to be stopped.
> Don't scale up stopped serves

- pkg/worker/runc_server.go
I noticed there were was a hanging build container, which seemed to have tried to shut down but was still blocked in an "archiving image" state:
```
2024/09/18 03:02:39 Creating a new archive from directory: /dev/shm/build-af70c46c/layer-0/merged
2024/09/18 03:03:06 <build-af70c46c> - container still running: 53fd754ed84aed3c
2024/09/18 03:03:36 <build-af70c46c> - container still running: 53fd754ed84aed3c
2024/09/18 03:04:06 <build-af70c46c> - container still running: 53fd754ed84aed3c
2024/09/18 03:04:36 <build-af70c46c> - container still running: 53fd754ed84aed3c
2024/09/18 03:05:06 <build-af70c46c> - container still running: 53fd754ed84aed3c
2024/09/18 03:05:36 <build-af70c46c> - container still running: 53fd754ed84aed3c
2024/09/18 03:06:06 <build-af70c46c> - container still running: …
```
> Fix hanging build container

- pkg/abstractions/taskqueue/serve.go
same idea as https://github.com/beam-cloud/beta9/pull/539, but for task queue
> remove serve lock when connection is lost for task queue serve

- pkg/gateway/middleware.go
- pkg/gateway/middleware_test.go
- pkg/repository/backend_postgres.go
- pkg/repository/base.go
- Stub function name is not always the same as deployment name
- Return deployment name in query
- Override parsed fields with deployment name
Resolve BE-1820
> Fix subdomain routing with different deployment name

- pkg/common/events.go
- pkg/common/redis.go
- pkg/worker/worker.go
- pkg/worker/worker_test.go
This will prevent workloads from using up all the memory available on a host which can cause a worker to get OOM'd by the kernel leaving the pod in a bad state.
Resolve BE-1780
> Add CPU and memory limits to runc containers

- pkg/common/url.go
- pkg/common/url_test.go
- pkg/gateway/middleware.go
- pkg/gateway/middleware_test.go
- Since subdomains can only be 64 characters long, public URL subdomains will only be the StubID.
- Improve regex logic by replacing name/hash with stub group
- Use Host and not Hostname when generating URLs to preserve the port
- Update tests
Resolve BE-1841
> Make public URL's subdomain just the StubID

- pkg/common/url.go
- pkg/common/url_test.go
- pkg/gateway/gateway.go
- pkg/gateway/middleware.go
- pkg/gateway/middleware_test.go
- Make deployment URLs the same regardless if public/private
- Cache the subdomain and handler path after database lookup
- Fix public path-based urls
Resolve BE-1841
> Make deployment URLs the same regardless if public/private

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/base/__init__.py
- sdk/src/beta9/abstractions/base/runner.py
- sdk/src/beta9/sync.py
This PR fixes functions in Colab. The main issue was that beam was not found in the last frame in the stack did not include a beam import. As a result, the beta9 config was being picked up. 
To fix this, I added a condition to check if beam is in the sys modules (its presence there would imply it was imported). I think we might be able to replace the frame logic entirely with this check. Aside from that, I've added some error handling to the file syncing and added some default ignore paths for google drive.
> Functions in Colab

- pkg/api/v1/deployment.go
- pkg/gateway/services/deployment.go
Recently discovered we have duplicated logic for stopping containers between the HTTP and gRPC services. This adds stop scheduled job logic to the HTTP service.
Resolve BE-1859
> Stop scheduled jobs from the HTTP frontend

- pkg/api/v1/stub.go
- pkg/common/config.default.yaml
- pkg/common/url.go
- pkg/common/url_test.go
- pkg/gateway/gateway.go
- pkg/gateway/middleware/subdomain.go
- pkg/gateway/middleware/subdomain_test.go
- pkg/gateway/services/stub.go
- pkg/repository/backend_postgres.go
- pkg/repository/backend_postgres_migrations/016_subdomains.go
- pkg/repository/backend_postgres_test.go
- pkg/repository/backend_utils.go
- pkg/repository/backend_utils_test.go
- pkg/repository/base.go
- pkg/types/backend.go
- pkg/types/config.go
- sdk/pyproject.toml
- sdk/src/beta9/abstractions/base/runner.py
- sdk/src/beta9/abstractions/endpoint.py
- sdk/src/beta9/abstractions/mixins.py
- sdk/src/beta9/abstractions/taskqueue.py
- sdk/src/beta9/cli/deployment.py
- sdk/src/beta9/cli/serve.py
- Replace stub.group with deployment.subdomain column in the database. This simplifies creating stubs again and moves the subdomain to the model (deployment) that its actually for.
- Fix generating subdomain hash by using deployment.name instead of stub.name. This makes deployment subdomains unique by deployment.name, stubType, and workspaceId.
- Introduce a new setting to control the invoke url type end-users should see in the UI and CLI. This also removes the localhost hardcode and simplifies URL building logic.
- Add a column check constraint on deployment.subdomain
- Move subdomain middleware to a new middleware package
- Update all tests
Resolve BE-1849 BE-1848
> Rework and fix subdomain routing

- pkg/gateway/middleware/subdomain.go
Only cache routes when a versioned or stub ID (e.g. serve) host is used. This ensures that non-versioned or "latest" hosts will always get the latest version of the callable.
Resolve BE-1860
> Don't cache latest version in subdomain middleware

- pkg/gateway/gateway.go
- pkg/repository/backend_postgres.go
Initially this would be used for database migrations. It is generic enough that it can be used in the future for other initialization locks.
In the database repo, this attempts to acquire a lock and when it does, a function is returned. This function is used to release the lock. If a lock is unable to be obtained, then the error is ignored and the system resumes normal operation. 
Resolve BE-1861
> Add init lock for gateway

- pkg/repository/backend_postgres_migrations/016_subdomains.go
There is a constraint on the subdomain column that does not allow double hyphens for DNS purposes. This migration generates the subdomain column and needs to remove double hyphens with a single hyphen before inserting into subdomain column.
Resolve BE-1849
> Don't allow double hyphens in subdomain name

- pkg/abstractions/endpoint/autoscaler.go
This fixes the issue where users with tasks pending have zombie endpoint serves.
> Remove running tasks from endpoint serve autoscaler

- deploy/charts/beta9/templates/_helpers.tpl
- pkg/api/v1/health.go
- pkg/gateway/gateway.go
- pkg/repository/backend_postgres.go
- pkg/repository/base.go
- Fails the HTTP health check if it cannot ping the database
- Pass readiness probe on just 1 successful check
- Lower readiness probe timeout to 1 second
Resolve BE-1866
> Ping database in health check

- sdk/src/beta9/runner/serve.py
This change should prevent the following error (which occurs when quickly starting/stopping a serve)
```
2024-10-02T13:18:02.950571248Z:
entry = (p, self.stat(p))
^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/beta9/runner/serve.py", line 57, in shutdown
self.observer.join(timeout=0.1)
File "/usr/lib/python3.11/threading.py", line 1114, in join
2024-10-02T13:18:02.950571269Z:
raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/local/lib/python3.11/dist-packages/beta9/runner/serve.py", line 116, in …
```
> add check to ensure observer exists before joining

- sdk/src/beta9/channel.py
- sdk/src/beta9/runner/function.py
- Marks the task status as error when it fails
- Fixes or prevents container from running until task expires e.g. "container still running"
- Fixes issue where CLI never exits - still mentions "Waiting..." even though the error has been printed
- Fixes scoping with some vars
Resolve BE-1904
> Fix: error handling in function runner

- sdk/src/beta9/exceptions.py
- sdk/src/beta9/runner/common.py
- sdk/src/beta9/runner/function.py
- Send exceptions/errors to callback if they happen
- Make Config fields required (not optional)
- Cleanup errors with custom exception classes
- Improve type annotations
Resolve BE-1904
> Send errors to callback url in function invocations

- sdk/src/beta9/channel.py
- sdk/src/beta9/runner/function.py
Fixes printing error logs in the function callable. It was removed during a refactor because the error logs were being printed twice, once in function:main() and once in with_runner_context.
To simplify this, we're decoupling the channel decorators and making it optional that the upstream error handler prints a stack trace. Also including a minor change in reordering params for handle_task_failure to be consistent with complete_task.
Resolve BE-1905
> Print error logs in function callable

- pkg/abstractions/common/ring_buffer.go
- pkg/abstractions/common/ring_buffer_test.go
- pkg/abstractions/endpoint/buffer.go
- pkg/abstractions/endpoint/endpoint.go
- pkg/abstractions/endpoint/task.go
- pkg/gateway/services/task.go
- pkg/task/dispatch.go
- pkg/types/task.go
Some quick fixes for endpoint request buffering, implements a lock-less flow control setup using tokens
- Instead of relying on locking, invert request counter to use token based flow control where max requests per container is equal to the number of available workers in the endpoint. This is very similar to the way it was before, but with more checks around capacity / combining set/get operations into a single atomic operation
- Check available containers without lock, _before_ trying to pop the request from the buffer to prevent unnecessary pops from fifo
- If requests are cancelled client side, cancel the tasks in the database / task dispatcher immediately
- Add priority flag to ring buffer to prioritize failed request retries before newer requests (also add some test cases for it)
- …
> Improve endpoint request buffering

- .github/workflows/release-changelog.yml
Removing condition. This might result in duplicate PRs when multiple releases go out at once, but I think closing duplicates is probably easier than remembering to add the tag line. 
I also added a temporary log of the release. I'm doing this so that I can test against a real release payload when making changes in the future.
> Remove condition and add temporary log

- pkg/abstractions/endpoint/task.go
We noticed that under heavy load tests, the top few tasks were stuck in pending. It turns out this was due to the echo context being used for task creation in backend_postgres. This makes sure we don't interrupt that sql operation.
> Fix race condition under load test with endpoint task creation

- pkg/abstractions/endpoint/buffer.go
- sdk/src/beta9/middleware.py
- sdk/src/beta9/runner/endpoint.py
The TaskMiddleware used the BasicMiddleware class which happened to skip the dispatch function if the type of http connection is a websocket conenction. This adds a new middleware to handle the task lifecycle functionality for just websockets
> Fix: Added middleware and passed request headers down from buffer for websockets

- pkg/abstractions/endpoint/http.go
Currently, only GET and POST work for ASGI applications.
None of these endpoints will work.
```python
@myapp.head("/head", summary="Test head method", description="This is a test")
async def head():
resp = Response(status_code=200)
resp.headers["X-Test"] = "test"
return resp
@myapp.put("/put")
async def put():
return {"message": "put"}
@myapp.delete("/delete")
async def delete():
return {"message": "delete"}
@myapp.options("/options")
async def options():
return {"message": "options"}
@myapp.patch("/patch")
async def patch():
return {"message": "patch"}
```
Before the change:
```bash
curl -X PATCH 'http://localhost:1994/asgi/asgi-test-app/latest/patch' \                                                           
-H 'Connection: keep-alive' \
-H 'Content-Type: application/json' \
-H …
```
> Fix: Allow any method for ASGI applications

- pkg/api/v1/base.go
- pkg/api/v1/container.go
When a container is already in the process of being stopped, this will return a 409 Conflict response instead of a 500 Internal Server Error. This is a better response for clients that need to understand whether or not a stop container request is already in progress.
Example of 409 according to Mozilla:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409#concurrent_tasks_disallowed
> Fix: Stop container response when already stopping

- sdk/pyproject.toml
- sdk/src/beta9/cli/volume.py
To fix an issue a user reported on Windows. 
https://docs.python.org/3.8/library/pathlib.html#pathlib.PurePath.as_posix
> Fix: Convert windows path to posix path

- sdk/pyproject.toml
- sdk/src/beta9/sync.py
- sdk/src/beta9/terminal.py
Resolve BE-1936
The first thing that this fixes is the `rich` status bar being contended for across threads. As things currently are, all the threads try to start their own status context manager. This is not allowed and we crash. With the change, I add a global status and a counter for the number of threads using it. If the status is already set, the thread just increments the counter and uses it. Then when its done it decrements the counter, which when zero triggers the status to be unset. This way, the global status is instantiated only once and lives until the last remote returns. 
Some changes were also made to file syncing. Previously each thread would attempt to do the syncing fully on its own. this caused race conditions in the backend when unarchiving the object. Now, only the …
> Fix: Support threaded execution of remote function

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/base/runner.py
Below you can see the get or create stub request to the gateway fail. This occurs because multiple requests are made with the same object id. Whichever call extracts the object first will succeed and any others will fail (assuming they go down the path of creating the stub). To fix this problem, I added a thread lock to the `get_or_create_stub` call in `prepare_runtime`. This guarantees that only one of the threads will try to create stub and the remaining threads will just retrieve the previously created stub instead of potentially trying to create one themselves. 
```bash
=> Building image 
=> Building image 
=> Building image 
=> Using cached image 
=> Syncing files 
=> Using cached image 
Reading .beta9ignore file
=> Using cached image 
Collecting files from …
```
> Fix: Add lock in sdk when creating stub to prevent races when using multiple threads

- sdk/pyproject.toml
- sdk/src/beta9/__init__.py
- sdk/src/beta9/abstractions/endpoint.py
- sdk/src/beta9/runner/endpoint.py
This is an experimental decorator that configures a basic websocket streaming example under the hood. The idea is to have a drop-in-place feature that lets users create streaming handlers that can do image generation, chat, etc. without writing the ASGI boilerplate.
**TODO**:
```
from beta9 import realtime
def load_model():
return "my_model"
@realtime(
cpu=1,
memory=128,
timeout=180,
concurrent_requests=10,
on_start=load_model,
authorized=False,
)
def handler(*, context, input: str):
print(context.on_start_value)
return input
```
The output from this echo server looks like this:
```
luke@Lukes-MBP beta9 % websocat ws://localhost:1994/asgi/public/bbfb4433-9685-4f79-9d92-68fb57b240c3
do something
do something
echo
echo
here
here
```
> Feat: Realtime abstraction built on top of asgi

- pkg/repository/container_redis.go
- pkg/types/scheduler.go
In a remote provider, we noticed this:
```
2024-10-21T00:46:11.860396431Z <taskqueue-527dc66c-0d37-4614-b078-3ca3f77fe603-4a686b40>  - container still running: 489898f6b7814f85
2024-10-21T00:46:11.936984064Z <taskqueue-527dc66c-0d37-4614-b078-3ca3f77fe603-4a686b40>:<53d0e79d-8203-46a2-8ea5-a151ef59412c>  - Epoch 284:   0%|          | 0/67 [00:00<?, ?it/s, v_num=0]
2024-10-21T00:46:11.980022059Z <taskqueue-527dc66c-0d37-4614-b078-3ca3f77fe603-4a686b40>  - container state not found, stopping container
2024-10-21T00:46:11.980043449Z <taskqueue-527dc66c-0d37-4614-b078-3ca3f77fe603-4a686b40>  - stopping container.
2024-10-21T00:46:11.991772502Z <taskqueue-527dc66c-0d37-4614-b078-3ca3f77fe603-4a686b40>  - container stopped.
2024-10-21T00:46:12.170090824Z Unmounting layer: …
```
> Fix: Add retries to update container state, increase container state ttl

- pkg/repository/base.go
- pkg/repository/container_redis.go
- pkg/scheduler/scheduler.go
- pkg/worker/lifecycle.go
- pkg/worker/runc_resources.go
- pkg/worker/worker.go
This PR mostly does 2 things.
- Move code around so worker.go isn't over 1k lines long
- Allow for the worker to terminate when a SIGTERM is received. This is done by having goroutines use select with ctx.Done to complete their loops and stopping (SIGKILL) all containers in the shutdown function.
- Move logic in processStopContainerEvents func to stopContainer func so stopContainer can be called elsewhere
- When calling stopContainer, do not check for container exit code. Container could still be running, terminate it anyway.
- Added listenForShutdown
- Forcefully stop all containers in the shutdown function. If we've gotten this far, containers should not be running otherwise unmounting clip images will hang.
- Moved calling of cancel() above stopping containers in shutdown. This stops …
> Feat: Allow Worker to shutdown when signaled with SIGTERM

- pkg/abstractions/endpoint/buffer.go
```
_, err := io.Copy(src, dst)
```
io.Copy doesn't automatically fail when `src` connection closes. 
This change guarantees that when at least connection fails (either src, dst) the other one also disconnects
> Fix: Client websocket connection hangs when server disconnects

- pkg/abstractions/endpoint/instance.go
- pkg/abstractions/taskqueue/instance.go
- pkg/api/v1/container.go
- pkg/api/v1/deployment.go
- pkg/gateway/services/container.go
- pkg/gateway/services/deployment.go
- pkg/gateway/services/worker.go
- pkg/scheduler/scheduler.go
- pkg/types/scheduler.go
- pkg/worker/lifecycle.go
- pkg/worker/worker.go
- Use struct as argument to stop a container
- Use struct on worker side to decide to force stop a container
- Update all references to scheduler.Stop to use struct argument
- Delete container instance after stopContainer called in worker. Otherwise, updateContainerStatus goroutine will send a [another] stop container event an and error will be printed.
Resolve BE-1948
> Feat: Add ability to force stop container via API

- .github/workflows/release-runner.yml
This adds micromamba to the runner release action. We set the tags based on the target.
> Add micromamba to runner action

- pkg/abstractions/image/build.go
- pkg/abstractions/image/build_test.go
This fixes custom base image parsing. In the example below, we currently drop the "nim" in the path. Any path greater than length two will have this same issue. To simplify things I have removed the "namespace" part of the regex and just capture the full repo path. I've added a test and fixed the test below. All previous tests still pass. 
```
{
ref:          "nvcr.io/nim/meta/llama-3.1-8b-instruct:1.1.0",
wantTag:      "1.1.0",
wantRepo:     "nim/meta/llama-3.1-8b-instruct",
wantRegistry: "nvcr.io",
},
```
> Fix: Capture full repo path when parsing custom base images

- pkg/abstractions/common/autoscaler.go
- pkg/abstractions/endpoint/autoscaler.go
- pkg/abstractions/endpoint/autoscaler_test.go
- pkg/abstractions/taskqueue/autoscaler.go
- pkg/abstractions/taskqueue/autoscaler_test.go
- pkg/common/config.default.yaml
- pkg/types/config.go
- Expose a maxReplicas config field to set a limit on how far a stub can scale up
> Feat: Make MaxReplicas configurable in gateway config

- sdk/src/beta9/channel.py
- sdk/src/beta9/runner/common.py
- sdk/src/beta9/runner/function.py
- fix a bug where exceptions raised while loading a handler are not visible to users in logs
> fix: bubble up exceptions invoking functions

- sdk/src/beta9/__init__.py
- sdk/src/beta9/abstractions/endpoint.py
- sdk/src/beta9/abstractions/integrations/__init__.py
- sdk/src/beta9/abstractions/integrations/vllm.py
- sdk/src/beta9/abstractions/integrations/vllm/vllm.py
- sdk/src/beta9/cli/deployment.py
- sdk/src/beta9/cli/serve.py
Resolve BE-1783
This PR adds a VLLM abstraction. Every argument you can provide to `vllm serve ...` is supported and can be passed into the vllm class or as part of the `EngineConfig`. The defaults are the same as the ones in vllm's repo. 
Here is a simple example of how it used: 
```python
from beta9 import integrations
e = integrations.EngineConfig()
e.device = "cpu"
vllm_app = integrations.VLLM(name="vllm-abstraction-1", engine_config=e)
```
And we deploy with:
```bash
beta9 deploy app.py:vllm_app
```
Serve with:
```bash 
beta9 serve app.py:vllm_app
```
Below is an example of serving the above on my local machine. 
In order to get deploying/serving a class to work, I introduced a `set_handler` method. The deploy and serve code now checks if that message is present and uses it to set …
> Feat: VLLM abstraction

- pkg/abstractions/function/function.go
- pkg/scheduler/pool.go
- pkg/scheduler/pool_external.go
- pkg/scheduler/pool_local.go
- pkg/scheduler/pool_sizing.go
- pkg/scheduler/pool_sizing_test.go
- pkg/scheduler/scheduler_test.go
Check if context is done in
- Provider's Reconcile func
- LocalKubernetesWorkerPoolController's deleteStalePendingWorkerJobs func
- RunCFunctionService's FunctionMonitor func
- WorkerPoolSizer's Start func
- Add exportable context on worker pool controllers
> Fix: exit more loops when context is cancelled

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/integrations/__init__.py
- sdk/src/beta9/abstractions/integrations/vllm.py
This PR makes two important corrections to the VLLM abstraction. 
First, it adds the secrets parameters. This is critical as it allows us to pass `HF_TOKEN` as a secret, which is required to download many of the models. 
Second, it adds a chat_template_url parameter. If set, we download this template and override the chat_template arg.
> Fix: Secrets, autoscaler, and chat templates for vLLM abstraction

- Makefile
- bin/delete_workers.sh
- pkg/gateway/services/task.go
- pkg/repository/backend_postgres.go
- pkg/types/filters.go
- sdk/src/beta9/cli/task.py
We had some of these filters before. I think the functionality was lost when we moved to using Squirrel.
This re-adds `stub-id`, `stub-name`, and `stub-type`, but in this iteration, all of these can now accept multiple values (comma delimited). And this adds new filter fields `container-id` and `task-id`. Lastly, all filter fields have a combination of names that are single, plural, hyphened, and underscored. 
Resolve BE-2026
> Feat: Add new filter fields to task list command

- pkg/scheduler/pool.go
- pkg/scheduler/pool_external.go
- pkg/scheduler/pool_local.go
- pkg/scheduler/pool_manager.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- pkg/types/config.go
- pkg/types/scheduler.go
- Adds an optional (default=false) preemptible flag
- Allows filtering of workers by request flags
- Allows filtering of worker pool controllers by request flags
**NOTE**: behavior of the schedule should not change unless we modify container requests going into the schedule with the `Preemptible=true` flag and add preemptible worker pools. By default they are all nonpremptible.
> Add pre-emptible flag to worker pool config

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/base/runner.py
- sdk/src/beta9/abstractions/endpoint.py
Resolve BE-2020
Instead of `curl`, we will now output a command that uses `websocat`. We do this by checking for a `websocket` flag set on the parent. 
```bash
~/Dev/be/baps/realtime main ❯ beta9 serve app.py:handler                                                          28s   beta9-py3.12
=> Building image
=> Using cached image
=> Syncing files
Reading .beta9ignore file
Collecting files from /Users/minzi/Dev/beam/baps/realtime
Added /Users/minzi/Dev/beam/baps/realtime/app.py
Collected object is 405.00 B
=> Files already synced
=> Invocation details
websocat 'ws://localhost:1994/asgi/id/ba11d9f7-7c2a-4396-8dd2-094f9c592301' \
-H 'Authorization: Bearer TOKEN'
=> Watching '/Users/minzi/Dev/beam/baps/realtime' for changes...
[2024-11-04 20:21:01 +0000] [10] [INFO] Starting gunicorn 20.1.0 …
```
> Fix: Output useful example command when deploying or serving realtime app

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/integrations/__init__.py
- sdk/src/beta9/abstractions/integrations/vllm.py
I compared what we had against what the vllm serve command supports and made a few tweaks. I also decided to just have one big vllm args class instead of two different ones. It didn't feel very obvious what their different purposes were and at the end of the day they're all just derived from the same pool of vllm serve cli arguments. 
I've also added tool parser validation that is in line with what vllm serve does
> Update and consolidate vllm args

- bin/delete_workers.sh
- pkg/types/worker.go
- pkg/worker/lifecycle.go
- pkg/worker/runc_server.go
- pkg/worker/worker.go
- Don't delete container state or instance in stopContainer func
- Don't stop all containers in shutdown func
- Call stopContainer in clearContainer func right before delete container state is called only if the container is still running. This allows the container to terminate when the global context is cancelled and finish executing the finalizeContainer and clearContainer functions. Also, this is needed when there is a sigterm, but not when the container stops normally.
- Don't use time.Sleep to delete container state and instance. Instead use a select statement that waits for either the graceful timeout or for the global context to cancel.
- Enable runc debug mode when global debug is enabled
- Revert delete worker changes
Resolve BE-2038
> Fix: worker hangs on shutdown

- sdk/pyproject.toml
- sdk/src/beta9/__init__.py
- sdk/src/beta9/integrations.py
This makes it so that we can import like this
```python
from beta9.integrations import VLLM
```
instead of 
```python
from beta9.abstractions.integrations import VLLM
```
> Better import for integrations

- sdk/pyproject.toml
- sdk/src/beta9/sync.py
Adds nested .venv to the default ignore list
> Fix: Add nested venv in ignore

- pkg/worker/lifecycle.go
I have not been able to reproduce this issue locally, which has made finding a solution difficult. As a result, I am proposing adding additional logs to get a better sense of what is actually happening here. 
My original guess was that we were leaking the routine. This would explain the failure to watch as it the process its watching wouldn't exist. 
I based it off of the following logs, which I've annotated with `worker-1` and `worker-2` for clarity. 
```bash
worker-1 2024-11-04T18:18:19.850004286Z:[1;36m(VllmWorkerProcess pid=50)[0;0m
Loading safetensors checkpoint shards:  50% Completed | 1/2 [02:34<02:34, 154.37s/it]
worker-1 2024-11-04T18:19:02.434508425Z:[2024-11-04 18:19:02 +0000] [1] [INFO] Handling signal: term
worker-2 2024-11-04T18:19:19.246985322Z:Loading image: …
```
> Add extra logging and tweak logic

- pkg/abstractions/common/instance.go
- pkg/abstractions/common/logs.go
- pkg/abstractions/endpoint/buffer.go
- pkg/abstractions/endpoint/serve.go
- pkg/abstractions/function/function.go
- pkg/abstractions/taskqueue/serve.go
- pkg/common/contexts.go
- pkg/gateway/gateway.go
- pkg/worker/runc_server.go
- Improve shutdown logic by running server (gRPC/HTTP) shutdowns and global context cancellation in parallel
- Merge global and local contexts to avoid modifying downstream code that doesn't need to know about the global context
- In the runc_server.go RunCStreamLogs func, make sure we can cancel the loop if the gateway is being shutdown 
- Cancel RequestBuffer heartBeat func if gateway is shutting down
> Fix: Improve shutdown logic, add more context done checks

- pkg/abstractions/image/build.go
- pkg/common/config.default.yaml
- pkg/types/config.go
- Use python-build-standalone as a drop-in replacement for custom images without python
- Template the install script, python versions, and a few other runtime variables
Resolve BE-1974
> Feat: Use python-build-standalone over apt packages

- pkg/gateway/services/stub.go
- Handle empty strings from older sdks in `Extra` field
> Fix: check if in.extra is an empty string for backwards compat with older SDKs

- pkg/common/config.default.yaml
Uses the versions available for a particular release.
Resolve BE-1974
> Fix: Update default values for python-build-standalone

- pkg/worker/base_runc_config.json
We should mount the sdk to the `opt/conda` path. This is used for a lot of images that use Anaconda like [pytorch](https://github.com/pytorch/pytorch/blob/main/Dockerfile#L24) and the [official anaconda image](https://github.com/anaconda/docker-images/blob/main/anaconda3/debian/Dockerfile#L4)
> Fix: mount sdk to opt conda path

- pkg/common/keys.go
- pkg/repository/base.go
- pkg/repository/worker_redis.go
- pkg/scheduler/pool_sizing.go
- pkg/scheduler/pool_sizing_test.go
- Add lock by pool name when adding workers in occupyAvailableMachines func. This prevents multiple instances of gateway from adding workers to the same pool at the same time
Resolve BE-2045
> Fix: Race condition when adding workers on remote nodes

- pkg/scheduler/pool_sizing.go
These log messages just mean that another gateway or goroutine is working on this. They're emitted every second x N workers running so it creates a bunch of noise.
Resolve BE-2045
> Fix: Prevent logging lock not obtained messages

- pkg/abstractions/taskqueue/taskqueue.go
- sdk/src/beta9/runner/common.py
In TaskQueuePop we claim a task and then update the "task running lock" TTL. When the task cannot be claimed, we return a nil/None object to the Python runner when its expecting a TaskQueuePopResponse object. This causes the spawned Python process to crash. In this scenario, TaskQueueComplete is never called which is also an issue because the "keep warm lock" TTL is never updated. 
For the AutoscaledInstance of a task queue, the StopContainersFunc has a pointer to stopContainers which calls stoppableContainers. In stoppableContainers, a container is considered stoppable when there is no "keep warm" or "task running" locks. THIS is why a container that should keep running is ultimately stopped.
A side affect of the Python process crashing is that the monitor_task function thread keeps …
> Fix: Claiming a task and prevent process crashes

- pkg/worker/image.go
- pkg/worker/lifecycle.go
- pkg/worker/worker.go
When the goroutine in clearContainer() is unblocked by the select (grace period has expired or worker receives a SIGTERM), then its really time to stop the container. In this case, we're going to send a SIGKILL to it instead of a SIGTERM.
This might fix the issue related to unmounting images.
> Fix: Send a SIGKILL to container when its really time to stop

- pkg/abstractions/experimental/bot/bot.go
- pkg/abstractions/experimental/bot/http.go
- pkg/abstractions/experimental/bot/types.go
- sdk/src/beta9/abstractions/endpoint.py
- sdk/src/beta9/abstractions/experimental/bot/bot.py
- sdk/src/beta9/abstractions/taskqueue.py
Same process as the other abstractions - use with assumed stub auth to allow unauthorized access to bots.
Used like this:
```
bot = Bot(
model="gpt-4o",
api_key="sk-proj-....",
locations=[
BotLocation(marker=HostLocation),
],
description="Scan hosts and determine what services are running on them",
authorized=False,
)
```
>  Feat: Add authorized flag to bots to allow public bot pages

- sdk/pyproject.toml
- sdk/src/beta9/runner/taskqueue.py
The early return caused `monitor_task.cancel()` not to be called which would snowball into the taskqueue shutting down early and the task never getting retried.
> fix bug with retry for causing taskqueue to spin down 

- go.mod
- go.sum
- pkg/worker/image.go
- pkg/worker/worker.go
- sdk/src/beta9/runner/taskqueue.py
- Fix a bug where cache discovery wasn't properly handling new hosts
- Always print exception during retries
- Wait for at least a single blobcache host
> Fix: handle cache discovery properly

- pkg/worker/lifecycle.go
Resolve BE-2052
This small change guards against trying to open the channel with canceled context.
> Fix: Add context guard to opening runc events channel

- sdk/src/beta9/abstractions/integrations/vllm.py
I'm pinning the versions in this PR so that we can have new builds triggered when updating these deps. I also added some of the new engine args added in the latest release of vllm.
> Fix: Pin latest versions and update engine args for vllm

- pkg/repository/backend_postgres.go
- pkg/repository/backend_postgres_migrations/018_add_stubid_index_task.go
- pkg/repository/backend_postgres_test.go
Resolve BE-2086
With these changes the query from the `listTaskWithRelatedQueryBuilder` should come out looking like this: 
```sql
SELECT
t.*,
w.external_id AS "workspace.external_id",
w.name AS "workspace.name",
s.external_id AS "stub.external_id",
s.name AS "stub.name",
s.config AS "stub.config",
s.type AS "stub.type",
d.external_id AS "deployment.external_id",
d.name AS "deployment.name",
d.version AS "deployment.version"
FROM
task t
JOIN workspace w ON t.workspace_id = w.id
JOIN stub s ON t.stub_id = s.id
LEFT JOIN deployment d ON s.id = d.stub_id
WHERE
t.workspace_id = $1
AND t.stub_id IN (SELECT id FROM stub WHERE external_id IN ($2))
```
instead of looking like this
```sql
SELECT
t.*,
w.external_id AS "workspace.external_id",
w.name AS "workspace.name",
s.external_id AS …
```
> Fix: Use indexed stub_id for task query instead of external id

- sdk/pyproject.toml
- sdk/src/beta9/runner/common.py
It seems `Value` is responsible for leaking the semaphore. Even though it is not used in the serve, the value is initialized on import because it is global. This tweak fixes the leak. 
Before
```
=> Stopping serve container
Goodbye 👋
/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d '
```
After
```
=> Stopping serve container
Goodbye 👋
```
> Fix: Dont init multiprocessing Value unless it will be used

- docker/Dockerfile.runner
Resolve BE-2125
This is a small change to the runner dockerfiles to fix Mamba builds by adding the bzip dependency and to fix the Python 3.12 build by removing disutils (see below). 
> Of note, the distutils package has been removed from the standard library.
https://docs.python.org/3/whatsnew/3.12.html
> Fix: Add bzip for Mamba and remove distutils for Python 3.12

- docker/Dockerfile.runner
Resolve BE-2112
This seems to be a breaking change made to the setuptools library and the maintainer does not seem likely to fix it. 
https://github.com/pypa/setuptools/issues/4483
It feels bad to be pinning an old version, but for now that seems to be the best way of mitigating this problem.
> Fix: Pin setuptools to working version for Python versions older than 12

- pkg/abstractions/endpoint/buffer.go
- pkg/abstractions/endpoint/endpoint.go
- pkg/abstractions/endpoint/task.go
- Uses key events + request heartbeats to correct for token drift after a particular gateway crashed unexpectedly
The consequence of this is that if a gateway that was actively handling a request crashes or is forcibly terminated, there will be a 30 delay before any active containers that were handling requests have the token count incremented. This should fix "bricked" containers that had an inaccurately low token count.
> Fix: Use heartbeats to correct for request token drift

- pkg/abstractions/common/instance.go
- pkg/abstractions/endpoint/instance.go
- pkg/scheduler/pool_manager.go
- pkg/scheduler/pool_manager_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- Add the ability to select multiple CPU pools in the scheduler
**NOTE**: technically GetPoolsByGPU is redundant with these changes, but to minimize scheduling changes I left it in use for GPU workloads.
> Feat: Support multiple cpu pools

- sdk/pyproject.toml
- sdk/src/beta9/__init__.py
- sdk/src/beta9/abstractions/function.py
- sdk/src/beta9/abstractions/taskqueue.py
- sdk/src/beta9/runner/taskqueue.py
- Fix tasks being marked as completed when they raise an exception and retry_for is not explicitly set
- Fix type hinting for retry_for in task_queue decorator
- Fix potential scoping issues with args and kwargs
- Remove unimplemented retry_for parameter from functions
Resolve BE-2128
> fix: task queue tasks should error when they raise an exception

- .vscode/settings.json
- pkg/abstractions/output/output.go
- pkg/api/v1/stub.go
- pkg/common/config.default.yaml
- pkg/gateway/gateway.go
- pkg/gateway/services/stub.go
- pkg/scheduler/pool_external.go
- pkg/scheduler/pool_local.go
- pkg/types/config.go
Change 
```
gateway:
externalHost: gateway.stage.beam.cloud
externalURL: http://localhost:1994
....
grpc:
....
http:
....
```
to 
```
gateway:
host: beta9-gateway.beta9
....
grpc:
externalHost: localhost
externalPort: 1993
tls: false
....
http:
externalHost: localhost
externalPort: 1994
tls: false
....
```
The ExternalURL value was less flexible
> Chore: Clean up gateway config

- sdk/pyproject.toml
- sdk/src/beta9/runner/endpoint.py
Resolve BE-2148
Previously, if the handler raised an exception it would be returned with status 200 and the task would be marked complete. With this change, the exception is returned with status 500 and the task is marked as errored.
> Fix: Endpoint returns internal service error on exception

- pkg/abstractions/taskqueue/task.go
In some cases, for a very long running task queue task the dispatcher can accidentally move a task to "Expired", even though it is actually completed. This happens because the task is finished, and there is a race condition in the dispatcher trying to "expire" the task and the task claim release.
> Fix: fix task cancellation status bug

- sdk/pyproject.toml
- sdk/src/beta9/runner/endpoint.py
Temporarily reverting the endpoint status change so that we can give users a longer warning period before making this change.
> Revert endpoint change

- pkg/abstractions/endpoint/buffer.go
Instead of directly writing the headers into the final response, make a copy and then write from the copy. 
> fatal error: concurrent map iteration and map write
> Fix: Write response headers from copy of internal response's headers

- pkg/worker/runc_server.go
For some reason this was causing our base requirement installation to fail. I suspect it might have been duplicating some of the env vars from the base spec, which might have been causing issues. We should investigate adding the vars not already included and see if that still causes issues. For now, this seems to fix the problem.
> Fix: Remove instance spec from exec env

- pkg/repository/events.go
- pkg/types/event.go
1. Sanitize container requests before sending data to events so that events don't leak vital information
2. Add stub_id directly into `container.lifecycle` events for easier filtering
> Chore: Sanitize container requests and add stub id to container events

- pkg/abstractions/image/build.go
At the moment, we will timeout after 3 minutes with the message 
```
Build failed: Timeout: container not running after 180 seconds.
```
This makes sense if we are pulling an image, but some dockerfile builds will take longer than this.
> Fix: Dont timeout during dockerfile builds

- pkg/abstractions/image/build.go
Resolve BE-2194
This changes the "Unknown error occurred" build messages to include the actual error that occurred. 
In some cases, this might help a user fix their build. Otherwise, it will at least give us more information to work off of.
> Always return actual error during builds

- pkg/abstractions/taskqueue/client.go
- pkg/abstractions/taskqueue/instance.go
- pkg/abstractions/taskqueue/keys.go
- pkg/abstractions/taskqueue/taskqueue.go
Not the most elegant approach, but this index will remove the scan (which locks redis). It should make us less susceptible to CPU spikes.
- Remove the last major redis key scan we perform in the beta9 repo (outside of maps)
> Fix: Remove task running lock scan

- pkg/repository/base.go
- pkg/repository/events.go
- pkg/types/event.go
- pkg/worker/cr.go
- pkg/worker/lifecycle.go
Partially resolve BE-2141
This PR makes a small addition to the OOM watching logic. It adds an additional `PushContainerOOMEvent` to the elastic search event repo. It is called when OOMs occur. In the frontend, we can use the container ID and stub ID to alert users that one of their containers has OOM issues.
> Send oom event to es

- pkg/abstractions/image/build.go
- pkg/worker/image.go
- pkg/worker/lifecycle.go
Resolve BE-2204
This PR adds additional logging to custom base image builds, increases the spin up timeout for build containers, and copies images to disk instead of memory with skopeo. The biggest change is the copying location. This change has little to no impact on the time it takes to copy/unpack custom images from what I've measured. It is a change worth making because it decreases the memory required by the worker for custom base images. For example, as things are, `docker.io/pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel` will cause the worker to OOM. With this change, that image can be used without any problems.
> Copy custom images to disk instead of memory before unpacking

- pkg/common/config.default.yaml
- pkg/scheduler/pool_external.go
- pkg/scheduler/pool_local.go
- pkg/scheduler/utils.go
- pkg/scheduler/utils_test.go
- pkg/types/config.go
Now that we copy image data into this directory, we need to increase its size for large images.
> Increase tmp size limit

- sdk/pyproject.toml
- sdk/src/beta9/channel.py
Fixes adding a user-agent to every gRPC connection. The UA will always be "beta9/x.x.x", even when called from the beam-client.
> fix: issue with getting package version for user-agent

- pkg/abstractions/image/build.go
- pkg/abstractions/image/build_test.go
Currently we don't use the digest even though we parse it correctly. This PR makes some minor tweaks to actually use the digest if one is provided.
> Fix: Use digest if one is provided in custom images

- sdk/src/beta9/runner/endpoint.py
Resolve BE-2148
Once the warning message has been circulated and users have had time to update any handling logic we can merge this. 
It is the exact same thing as https://github.com/beam-cloud/beta9/pull/791, but we need to wait to release
> Fix: Return error and exception when endpoint app raises an exception

- sdk/src/beta9/env.py
- sdk/src/beta9/multipart.py
- sdk/tests/test_env.py
> Remove thread local, expose printing retry errors

- pkg/abstractions/volume/multipart.go
- sdk/pyproject.toml
- sdk/src/beta9/multipart.py
- When file size is 0, make just 1 presigned url upload part
- When upload is complete, call progress callback at least once to indicate it completed
- Don't send any data to juicefs s3 gateway when chunk is empty
- Fix divide by zero errors with downloads
Resolve BE-2133
> fix: multipart uploads and downloads with empty files

- sdk/src/beta9/cli/volume.py
- Fixes some edge cases when cancelling during a copy - resets the terminal cursor so it is shown even after an error
Resolve BE-2133
> fix: show terminal cursor after multipart error

- pkg/worker/image.go
It might be runner image, which is not custom
> Change log to say base image instead of custom base image

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/base/__init__.py
- sdk/src/beta9/cli/main.py
Prevent these logs from showing up when running a function.
```python
#!/usr/bin/env python
from beam import function
@function(name="func-test", cpu=3, memory="16Gi")
def handler():
return {}
if __name__ == "__main__":
handler.remote()
```
```sh
python app.py
...
=> Function complete <99f6ef8f-749a-43e2-a1e6-e9e55c794f0d>
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1737223352.040854 11801855 init.cc:232] grpc_wait_for_shutdown_with_timeout() timed out.
```
Resolve BE-2262
> fix: attempt to disable gRPC absl logs

- pkg/worker/base_runc_config.json
Certain images install stuff into /root. We currently overwrite this path with a tmpfs on container startup. I don't think this is needed, because we are already adding a r/w overlay on top of the user container that allows them to modify the contents. For example, this should work:
```
from beta9 import Image, endpoint
@endpoint(
cpu=1,
memory=128,
image=Image(
python_version="python3.10",
).add_commands(
[
"touch /root/hello.txt",
"touch /something.txt",
]
),
)
def handler():
with open("/root/hello.txt", "r") as f:
print(f.read())
with open("/root/something_else.txt", "w") as f:
f.write("Hello, World!")
return "Hello, World!"
```
> Fix: don't overwrite /root in containers

- pkg/worker/runc_server.go
Resolve BE-2274
This did not fix unsloth issues, but is generally important for GPU builds. It will also be important for custom image builds once we start propagating their environment variables as well.
> Fix: Runc exec should use running container's env vars

- Makefile
- docker/Dockerfile.runner
- pkg/abstractions/shell/http.go
- pkg/abstractions/shell/shell.go
- sdk/src/beta9/abstractions/mixins.py
- sdk/src/beta9/abstractions/shell.py
- Use GET over CONNECT since CONNECT is a tunnel
- Use newer paramiko method to authenticate with
- Add https support to endpoint
- Set keepalive and remove any deadlines on proxied shell connnections
- Notify SDK when to proceed with establishing Paramiko SSH connection after connection to container has been established
- Syntax updates to runner dockerfile
- Use plain console logs when building images for runners
Resolve BE-2267
> fix: improve beam shell connectivity

- sdk/pyproject.toml
- sdk/src/beta9/cli/worker.py
- `worker cordon/uncordon` can accept multiple worker ids
- `worker cordon/uncordon` can accept from stdin with `-`
- Fix `worker drain` docs
Resolve BE-2275
> feat: allow cordon/uncordon multiple workers in one go

- pkg/abstractions/image/build.go
- pkg/types/worker.go
- sdk/pyproject.toml
- sdk/src/beta9/abstractions/base/runner.py
- sdk/src/beta9/abstractions/experimental/bot/bot.py
- sdk/src/beta9/abstractions/image.py
- Remove "is valid" message since we already print an error if the build options fail
- More descriptive container exit code errors
- Improve build image error rendering
- Print image build error message once
- Fix some type hinting
Resolve BE-2219
> fix: image build error messaging

- docker/Dockerfile.worker
- pkg/worker/nvidia.go
- pkg/worker/nvidia_test.go
Resolve BE-2270
This PR does three things 
1. It upgrades the worker to CUDA 12.4.
2. If CUDA_HOME is not set or provided anywhere, use a default location for CUDA 12.4
3. Install encode, decode, nvcc, compute, utils, etc in worker. This all ends up available through mounts so runner size/cold start will not be impacted. 
WARNING: Do not release until A10G cuda version/driver is updated
> Fix: Upgrade to Cuda 12.4, use defaults for missing env vars, include more libs

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/function.py
Right now its not handled at all.
```bash
~/Dev/beta9/t/custom-image main M:1 ❯ python app.py                                                           ✘ INT 2m 17s   beta9-py3.12   system minzi@nobara
=> Building image 
Using custom base image: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
Exiting shell, stopped build.
```
> Fix: Cleaner handling when cancelling a function during build stage

- sdk/src/beta9/channel.py
- sdk/src/beta9/runner/function.py
The issue here is that during a rollout restart, the stream exits with no errors (since the function service context causes the stream to exit). So in those cases, we stop setting heartbearts and create "ghost tasks". The solution is to embed the monitor task into an outer loop, and if we encounter an interruption of the stream without any errors, just restart the monitor_task stream. You can see this reflected in the logs below, after a rollout restart, the loop restarts:
```Response(ok=True)"}
{"level":"info","container_id":"function-d6c67c57-e539-48ed-83bd-3b1d73c72fdd-ca6d2830","task_id":"d6c67c57-e539-48ed-83bd-3b1d73c72fdd","time":"2025-02-02T18:05:16Z","message":"Received monitor response: FunctionMonitorResponse(ok=True)"} …
```
> Fix: prevent stream exit from messing with function runs

- cmd/worker/main.go
According to the zerolog docs
> Err adds the field "error" with serialized err to the *Event context. If err is nil, no field is added.
So we don't actually need to printf the error. This reverts the change.
> fix: revert worker fatal err message

- sdk/pyproject.toml
- sdk/src/beta9/cli/task.py
- `stop task` can accept multiple task ids
- `stop task` can accept multiple task ids from stdin
Resolve BE-2317
> feat: stop task accepts many tasks or stdin

- go.mod
- go.sum
Blobcache Changes
* Fix contention issues, hotfix for GC by @luke-lombardi in https://github.com/beam-cloud/blobcache-v2/pull/24
* readahead tuning by @luke-lombardi in https://github.com/beam-cloud/blobcache-v2/pull/25
* fix: concurrent map iteration and map write panic by @nickpetrovic in https://github.com/beam-cloud/blobcache-v2/pull/26
Resolve BE-2332
> fix: worker blobcache panic

- pkg/abstractions/volume/multipart.go
- sdk/pyproject.toml
- sdk/src/beta9/exceptions.py
- sdk/src/beta9/multipart.py
- Return user-friendly error message when volume is not found during creating, completing, or aborting a multipart upload
- List and Stat path errors get their own error classes in order to differentiate between them
Resolve BE-2333
> feat: improve multipart error messages

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/image.py
If the local environment is using Python 3.13, the version detection will cause a ValueError.
> Fix: Local Python 3.13 causes a value error

- pkg/common/proc.go
- pkg/storage/juicefs.go
- pkg/worker/events.go
When resource limits/requests are configured, the worker gets a oom_score_adj of -997 (or not -1000), but all juicefs processes get -1000 which means they are not oom-killable. 
This is mentioned in the [oom_score_adj](https://man7.org/linux/man-pages/man5/proc_pid_oom_score_adj.5.html) man page. 
> The value of oom_score_adj is added to the badness score
> before it is used to determine which task to kill.
> Acceptable values range from -1000 (OOM_SCORE_ADJ_MIN) to
> +1000 (OOM_SCORE_ADJ_MAX).  This allows user space to
> control the preference for OOM-killing, ranging from always
> preferring a certain task or completely disabling it from
> OOM-killing.  The lowest possible value, -1000, is
> equivalent to disabling OOM-killing entirely for that task,
> since it will always report a …
> fix: juicefs does not exit when the worker is oomkilled

- sdk/src/beta9/cli/task.py
Can be useful to know how much time is passing between when the task was created and when it actually starts/ends.
> add created at to task list

- pkg/common/config.default.yaml
- sdk/src/beta9/channel.py
- sdk/src/beta9/runner/taskqueue.py
Previously this would fail:
```python
from beta9 import task_queue
@task_queue(
cpu=1.0,
memory=128,
name="big-payload",
)
def big_payload(input):
print("hello!")
print(input["x"][:100])
return {"result": "ok"}
if __name__ == "__main__":
print("starting...")
data = "a" * 10 * 1024 * 1024
big_payload.put({"x": data})
```
With this change it wont
> Fix: Receive up to 16mb payloads for taskqueue

- deploy/charts/beta9/templates/_helpers.tpl
- manifests/kustomize/components/beta9-gateway/deployment.yaml
- pkg/auth/grpc.go
- pkg/gateway/gateway.go
**Changes**
- Replaces HTTP health check with gRPC
- Enables gRPC reflection when in debug mode
- Configures aggressive readiness and liveness probes
**Summary**
This adds a new [gRPC health](https://grpc.io/docs/guides/health-checking/) endpoint. 
The new readiness probe values basically say the pod will _stop receiving traffic_ if the gRPC health endpoint fails for 6s (2s * 3s). It also runs every 3 seconds. Alternatively, this starts sending the pod traffic after 6s of successful checks.
The new liveness probe values basically say the pod will _restart_ if the gRPC health endpoint fails for 30s (10s * 3s). It also runs every 3 seconds. Alternatively, this will not restart the pod after 6s of successful checks.
Because the liveness checks take no more than 30s, the shutdown timeout will …
> feat: Use gRPC Health Check server

- deploy/charts/beta9/templates/_helpers.tpl
- manifests/kustomize/components/beta9-gateway/deployment.yaml
Fixes helm upgrades. Should prevent this error.
```
Error: UPGRADE FAILED: cannot patch "beta9-gateway" with kind Deployment: Deployment.apps "beta9-gateway" is invalid: spec.template.spec.containers[0].livenessProbe.successThreshold: Invalid value: 2: must be 1
```
Kustomize seems unaffected and will just correct successThreshold to 1.
Resolve BE-2386
> fix: liveness probe success threshold

- pkg/scheduler/pool.go
- Prevents the deletion of jobs where its pods have already completed e.g. completed workers
Resolve BE-2343
> feat: check pod status before deleting stale jobs

- pkg/abstractions/common/instance.go
Move the forceful override of a nil autoscaler to the `Sync` method. 
The sync method is called on initial initialization of the autoscaled instance (NewAutoscaledInstance) as well as Load method in the InstanceController. 
We must have the nil autoscaler override snippet every time we do a sync because it will reload the StubConfig from the database anew.
> Fix: Nil Autoscaler on older stub configs

- pkg/storage/juicefs.go
This re-adds part of the previous juicefs process improvements. This should not run as a daemon because the daemon ends up forking another juicefs process and becomes defunct immediately. 
In some situations, when the worker is shutting down, it can't shutdown the forked juicefs process because the daemonized/parent juicefs process is already shutdown (zombied).
> fix: run juicefs in foreground within goroutine

- pkg/worker/gpu_info.go
- pkg/worker/gpu_info_test.go
There was some incorrect logic around the parsing of output from `nvidia-smi`. Refer to issue #984 for more context.
> Fix: Correctly format the PCI path when checking device existence

- Makefile
Its annoying to add the env var to the okteto.yaml file and then pick around that file when committing.
> Check for config.yaml and set env in okteto if it exists

- go.mod
- go.sum
- pkg/worker/image.go
- pkg/worker/lifecycle.go
With this change, we will explicitly re-populate cache in this call.
Depends on https://github.com/beam-cloud/blobcache-v2/pull/28
> stat and check content locality in lazy pull

- sdk/src/beta9/abstractions/container.py
- sdk/src/beta9/abstractions/endpoint.py
- sdk/src/beta9/abstractions/function.py
- sdk/src/beta9/abstractions/integrations/vllm.py
- sdk/src/beta9/abstractions/pod.py
- sdk/src/beta9/abstractions/taskqueue.py
- sdk/src/beta9/abstractions/volume.py
Resolve BE-2426
Adds cloudbucket to volumes docstring for a variety of abstractions.
> Fix: docstrings for volume's list to include cloud bucket

- pkg/worker/lifecycle.go
- pkg/worker/logger.go
Resolve BE-2427
The current log limits are imposed to build containers, which might prevent users from seeing critical build logs.
> Dont limit build logs

- sdk/pyproject.toml
- sdk/src/beta9/abstractions/pod.py
- sdk/src/beta9/abstractions/shell.py
- sdk/src/beta9/abstractions/volume.py
- sdk/src/beta9/terminal.py
Authorized needs to be set to true for the shell command to work. Also fixes an issue where it would try to reconnect after an `exit` (I think).
> fix: fix shell w/ pods

- pkg/abstractions/image/build.go
- pkg/common/io.go
- pkg/common/skopeo.go
- pkg/worker/image.go
- pkg/worker/lifecycle.go
- pkg/worker/logger.go
Added log that shows image load time when running container. 
Optionally stream the output of skopeo copy and inspect
> Feat: Add more client logs

- Makefile
- pkg/worker/criu_nvidia.go
* Changes the base working directory for restores to `/tmp` to avoid write issues with the cache/mountpoint-s3 filesystems.
> Write restore logs to tmp

- pkg/gateway/services/stub.go
Resolve BE-2415
This is a small change to simply fail serves when there is no immediate capacity to fulfill them.
> Fix: Warn users when trying to serve on hardware with no capacity

- bin/gen_proto.sh
Adds a check/warning to tell users if the binary is from the system (likely not the correct version).
> Add warning to gen proto

- pkg/abstractions/endpoint/instance.go
- pkg/abstractions/endpoint/serve.go
- pkg/abstractions/experimental/bot/http.go
- pkg/abstractions/image/build.go
- pkg/abstractions/image/image.go
- pkg/abstractions/pod/instance.go
- pkg/abstractions/shell/shell.go
- pkg/abstractions/taskqueue/instance.go
- pkg/abstractions/taskqueue/serve.go
- pkg/common/skopeo.go
- pkg/gateway/services/container.go
- pkg/gateway/services/deployment.go
- pkg/gateway/services/worker.go
- pkg/repository/container_redis.go
- pkg/types/scheduler.go
- pkg/types/worker.go
- pkg/worker/image.go
- pkg/worker/lifecycle.go
- pkg/worker/worker.go
- sdk/src/beta9/cli/container.py
Container stopped by scheduler because keep warm expired.
Stopping container with `beta9 container stop`
In the future it would be nice to send even more information along with scheduler stops.
> Fix: Improve exit code logging

- pkg/metrics/metrics.go
Having a potentially empty gpu field causes issues in grafana.
> Fix: Replace empty with none for prometheus metrics with gpu field

- pkg/abstractions/pod/http.go
- pkg/abstractions/pod/pod.go
- pkg/api/v1/stub.go
- pkg/repository/backend_postgres.go
- pkg/repository/backend_postgres_migrations/023_add_public_field_to_stub.go
- pkg/types/backend.go
**Summary**
This PR adds the ability to clone the stub only if it is public. The public field is necessary else user's can just clone any stub that exists.
I make sure to only clone information that can be shared. Secrets are repopulated from the user that is cloning the stub and will fail if the secrets do not exist. I also make sure to clone the object from parent.
**Running the stub**
Since each abstraction has its unique way of running their stub (functions vs pods), I do not try to condense their functionality into a umbrella `Run` method. That means you must call them from their individual invocation endpoints
function: /function/:id/:stubId
pod: /pod/run/:stubId
Notes:
- I assume that the object is free to clone if attached to a public stub
- I skipped cloning onDeploy stubs to …
> Feat: Add ability to clone stubs

- pkg/api/v1/stub.go
- pkg/api/v1/stub_test.go
If a user never created a stub from any sort of command, they won't have an existing folder `/data/objects/{workspace_name}`
> Fix: Copy content fails if user never created stub

- pkg/types/config.go
Added new configuration fields to support alternative authentication methods for Victoria Metrics monitoring. These fields will enable cleaner implementation of monitoring ingestion in the agent.
- Added three new fields to VictoriaMetricsConfig: WriteURL, WriteUsername, and WritePassword.
- Maintained backward compatibility with existing PushURL, AuthToken, and PushSecs fields.
* [#1081: Enhanced change log with LLM](https://github.com/beam-cloud/beta9/pull/1081)
* **[#1088: Add fields for monitoring ingestion config](https://github.com/beam-cloud/beta9/pull/1088)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/beam-cloud/beta9/pull/1088))
--- …
> Add fields for monitoring ingestion config

- pkg/worker/image.go
Fixed an issue where the system attempts to cache images when no hosts are available. This change prevents unnecessary caching attempts by checking host availability first.
**Bug Fixes**
- Added a check for available hosts before attempting to cache images
- Removed redundant logging message for image loading
* [#1081: Enhanced change log with LLM](https://github.com/beam-cloud/beta9/pull/1081)
* **[#1087: Fix: Check for available hosts before attempting to cache](https://github.com/beam-cloud/beta9/pull/1087)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/beam-cloud/beta9/pull/1087))
---
> Fix: Check for available hosts before attempting to cache

- pkg/api/v1/token.go
- pkg/repository/backend_postgres.go
- pkg/repository/backend_postgres_migrations/025_add_workspace_primary_token.go
- pkg/repository/base.go
- pkg/types/backend.go
Added support for primary workspace tokens with appropriate authorization controls. This enhancement allows creating a special token type with restricted access permissions.
- Added a new primary token type for workspaces
- Created database migration to add the primary token type to the enum
- Added endpoint to create primary tokens (restricted to cluster admins)
**Refactors**
- Enhanced token management with proper permission checks
- Added GetTokenByExternalId method to retrieve tokens by external ID
- Updated token deletion to prevent non-admin users from removing primary tokens
* [#1081: Enhanced change log with …
> Add primary tokens

- docker/Dockerfile.worker
Updated the Golang base image for nvidia-container-toolkit to version 1.23-bookworm. This fixes build issues with the nvidia-container-toolkit component in the worker Dockerfile.
**Bug Fixes**
- Updated the Golang base image from unspecified version to 1.23-bookworm for the nvidia-container-toolkit build stage.
* [#1081: Enhanced change log with LLM](https://github.com/beam-cloud/beta9/pull/1081)
* **[#1092: Fix: Nvidia container toolkit needs 1.23 to build](https://github.com/beam-cloud/beta9/pull/1092)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/beam-cloud/beta9/pull/1092))
---
> Fix: Nvidia container toolkit needs 1.23 to build

- go.mod
- go.sum
Reverted Go version from 1.23.0 to 1.22.10 and downgraded several dependencies to maintain compatibility. These changes roll back recent Dependabot updates that caused issues.
**Dependencies**
- Downgraded Go from 1.23.0 to 1.22.10
- Removed toolchain go1.24.1 directive
- Reverted golang.org/x/net from 0.36.0 to 0.35.0
- Reverted golang.org/x/crypto from 0.35.0 to 0.33.0
- Removed several intermediate blobcache-v2 dependency versions
* [#1081: Enhanced change log with LLM](https://github.com/beam-cloud/beta9/pull/1081)
* **[#1094: revert dependabot](https://github.com/beam-cloud/beta9/pull/1094)** ⬅️ Current PR ([View on …
> revert dependabot

- pkg/abstractions/volume/http.go
Fixed a bug in the file download endpoint where workspace references could be nil. This change properly fetches the workspace by ID before using it in the download process.
**Bug Fixes**
- Fixed potential nil pointer dereference by retrieving workspace information directly from the database
- Replaced dependency on auth context with explicit workspace lookup
- Added proper error handling when workspace ID is invalid
> Fix: Patch volume nil workspace reference

- sdk/src/beta9/cli/machine.py
Fixed the machine creation command to only include the flux branch parameter when it differs from "main". This prevents unnecessary branch specification when using the default main branch.
**Bug Fixes**
- Updated the create_machine function to only add the flux-branch argument when the branch is not "main"
> fix create command

- pkg/types/gpu.go
- sdk/src/beta9/type.py
Added support for the L40S GPU type across the platform. This enhancement expands our GPU offerings to include NVIDIA's L40S model in both the Go backend and Python SDK.
- Added L40S GPU type constant in the Go backend code.
- Updated the Python SDK to include L40S in the GpuType enum and GpuTypeLiteral list.
- Included L40S in the AllGPUTypes function to make it available throughout the system.
> Feat: Add L40S gpu type

- pkg/scheduler/utils.go
Added support for L40S GPU type in the scheduler's GPU parsing function. This change ensures the system can properly recognize and handle L40S GPUs when they're specified.
**Bug Fixes**
- Added missing case for L40S GPU type in the ParseGPUType function.
> Add missing l40s location

- pkg/abstractions/pod/proxy.go
Increased the connection read timeout for Pod Proxy from 10 seconds to 5 minutes. This change helps prevent timeouts during longer-running operations when proxying to containers.
**Bug Fixes**
- Extended the `connectionReadTimeout` constant from 10 seconds to 5 minutes in the pod proxy implementation.
Increases `connectionReadTimeout` from 10s to 5mins
> Fix: Increase connectionReadTimeout to 5min for Pod Proxy

- pkg/api/v1/machine.go
- pkg/repository/base.go
- pkg/repository/provider_redis.go
- pkg/scheduler/pool_external.go
- pkg/scheduler/pool_sizing.go
- pkg/types/provider.go
Added machine readiness and metadata mode to improve worker scheduling and connection management. These changes help the scheduler determine if a machine is ready for workers and prevent non-local node connections from using the sentinel connection.
- Added `Ready` boolean flag to machine state to indicate scheduling availability.
- Added `MetadataMode` field to control sentinel connection behavior for non-local nodes.
**Refactors**
- Updated `SetMachineKeepAlive` function signature to include the readiness parameter.
- Modified repository interfaces to support the new machine state properties.
This PR adds readiness and metadata mode to the machine state. Readiness will be used by the scheduler to determine if a machine is ready to have workers scheduled. The metadata …
> Fix: Add metadata mode to machine state

- pkg/gateway/services/container.go
Added exit code information to container stop messages for better debugging. This change helps users identify what went wrong when their container stops unexpectedly.
**Bug Fixes**
- Updated container stop message to include the actual exit code value.
- Improved error clarity by showing numeric exit codes alongside any existing exit code messages.
When we encounter an unexpected exit code we should log what it was. This exit code could from the user app and give them necessary information about what went wrong.
> Fix: Add unknown exit code to message for clarity

- pkg/scheduler/pool_external.go
- pkg/scheduler/pool_sizing.go
Reduced excessive error logging when scheduling workers by returning nil instead of errors for common conditions. This change prevents log spam when machines are not ready or out of capacity.
**Bug Fixes**
- Changed error returns to nil returns when machines are not ready or out of capacity
- Added handling for nil worker returns in the worker pool sizer
- Preserved the same functional behavior while eliminating unnecessary error logs
Currently it spams machine not ready and out of capacity
> Fix: Clean up logging around scheduling workers

- pkg/api/v1/workspace.go
- pkg/types/storage.go
Updated workspace storage bucket naming to use external IDs instead of internal numeric IDs. This change provides more stable and meaningful bucket names that won't change if internal IDs are regenerated.
**Refactors**
- Changed `WorkspaceBucketName` function to accept external ID (string) instead of internal ID (uint)
- Updated bucket name format from `workspace-{id}` to `workspace-{externalId}`
- Modified workspace storage creation to use external ID when generating bucket names
> use external id for storage bucket

- pkg/common/object.go
- pkg/worker/lifecycle.go
- pkg/worker/mount.go
Improved container code fetching by directly downloading stub code from S3 instead of relying on GeeseFS. This change avoids eventual consistency issues and provides a more reliable way to access container code.
**Refactors**
- Added direct S3 download functionality to fetch stub code objects instead of using the filesystem.
- Implemented zip extraction logic to unpack code directly from memory to the container workspace.
- Updated the container mount setup function to accept a context parameter for proper cancellation support.
**Bug Fixes**
- Fixed potential eventual consistency issues when accessing code through GeeseFS.
- Added path validation to prevent zip slip vulnerabilities during extraction.
To avoid eventual consistency problems with GeeseFS, we go direct to object storage for …
> Fetch and unpack stub code from s3

- pkg/api/v1/deployment.go
Added redirect to presigned URLs for deployment package downloads. This improves performance and security by using temporary authorized links instead of direct file serving.
- Added support for generating presigned URLs with a 10-minute expiration for deployment package downloads.
- Implemented HTTP redirect (307) to the presigned URL when a storage client is available.
**Refactors**
- Modified the DownloadDeploymentPackage handler to first attempt using presigned URLs before falling back to direct file serving.
> Redirect to presigned deployment package

- pkg/worker/usage.go
- pkg/worker/worker.go
Fixed GPU reporting in worker metrics by adding GPU type to container usage requests, ensuring accurate resource tracking and cost calculations.
> fix worker metrics gpu reporting

- pkg/api/v1/machine.go
- pkg/providers/remote_config.go
- pkg/repository/provider_redis.go
- pkg/scheduler/pool_external.go
- pkg/types/config.go
- pkg/types/provider.go
Removed the metadata mode field from remote machine configuration to simplify machine state management and reduce complexity.
> feat: dynamic remote machine config

- go.mod
- go.sum
Updated the blobcache-v2 dependency to the latest version to include recent fixes and improvements.
> fix: bump cache version

- bin/k3d.sh
- docker/Dockerfile.worker
- pkg/storage/geese.go
Switched to a custom geesefs fork with fixed symlink handling and enabled the --symlink-zeroed option for mounts.
- **Dependencies**
- Build geesefs from the beam-cloud fork instead of downloading the upstream release.
- Add --symlink-zeroed flag to geesefs mount command.
> Use geese fork with fixed symlinks

- sdk/src/beta9/abstractions/function.py
If a function times out, the sdk blows up on the user because it tries to load an empty result. 
Long term, we should add an exit code and render a warning in the terminal, but this will do for now. 
---
Fixed a bug where the SDK would crash if it tried to load an empty result after a function timeout.
> Fix: Dont try to load empty result

- pkg/repository/base.go
- pkg/repository/events.go
- pkg/types/event.go
- pkg/worker/lifecycle.go
Added container exit code to the container stopped event, so exit codes are now included in event data.
- **Event Changes**
- Updated event schema to include an exitCode field.
- Increased schema version to 1.2.
> Feat: Push container exit code to events

- pkg/repository/backend_postgres.go
- pkg/types/backend.go
Updated the time serializer to use nanosecond precision, allowing more accurate timestamps.
> Feat: Add nanosecond time for serializer time and add app to deployments

- pkg/scheduler/scheduler.go
Reduced the base delay for retrying failed requests from 5 seconds to 1 second to make retries faster and improve responsiveness.
- **Bug Fixes**
- Added error logs for failed scheduling and GPU assignment to help with debugging.
> fix: lower delay for retrying requests

- pkg/gateway/services/container.go
Cluster admins can now stop any container, regardless of workspace, fixing a permissions issue.
> Fix: Allow cluster admins to stop all containers

- pkg/types/config.go
Added a config_group field to WorkerPoolConfig to support grouping worker pool configurations.
> feat: add config group to worker pool config

- pkg/scheduler/pool_external.go
- pkg/scheduler/pool_local.go
Fixed the BLOBCACHE_LOCALITY environment variable to use the correct config group value in both external and local worker pools.
> fix locality setting

- pkg/api/v1/workspace.go
- pkg/common/config.default.yaml
- pkg/types/config.go
- pkg/types/storage.go
Made the workspace storage bucket prefix configurable through the config file, allowing custom prefixes for new workspace buckets.
- **Config Updates**
- Added defaultBucketPrefix to workspaceStorage config.
- Updated code to use the new prefix when creating workspace buckets.
> feat: allow bucket prefix to be configurable

- pkg/scheduler/pool_health.go
Fixed the pool health check to only count machines in the "ready" state as registered, preventing machines that are not fully ready from being included.
> fix ready machines check

- pkg/repository/backend_postgres_migrations/026_add_apps_table.go
- pkg/scheduler/pool_health.go
- pkg/types/scheduler.go
- pkg/types/types.proto
- sdk/src/beta9/clients/types/__init__.py
Fixed pool health checks to use the correct machine state and added a migration to create an app table with related updates to stubs and deployments.
- **Migration**
- Added new app table and linked it to stubs and deployments.
- Populated app data for existing records and handled stubs without an app.
- **Bug Fixes**
- Updated pool health logic to track ready machines instead of registered machines.
> fix: fix pool health, update migration script

- pkg/repository/backend_postgres.go
Added more stub fields (created_at, type, updated_at) to the latest deployments list for better data completeness.
> chore: include rest of stub information in list latest deployment

- hack/k3d.yaml
This small change just makes local development on a linux machine easier. There are permissions issues when building the worker once `.k3d` in the project directory. They re-appear everytime a PVC is created or modified, so easiest to just avoid having it in that directory.
---
Updated k3d.yaml to use a directory in the home folder instead of the project directory for storage and registry volumes. This avoids permission issues during local development on Linux.
> tweak k3d yaml

- pkg/common/config.default.yaml
- pkg/storage/geese.go
- pkg/types/config.go
- pkg/worker/storage_manager.go
Added support for custom mount options in the GeeseFS storage config.
- **New Features**
- Added a mountOptions field to GeeseFS config to allow passing extra mount options.
> add geesefs mount options

- pkg/api/v1/task.go
Reverted the use of the serializer in the retrieve task endpoint to return the raw task object directly.
> Revert serializer on retrieve task

- pkg/abstractions/common/stream.go
- pkg/common/key_events.go
Race occured when task completed between preliminary check and subscription start. Therefore we should do the backwards check after the subscriptions is established so that there is no gap. 
---
Fixed a race condition where tasks could complete before event subscriptions started, causing missed events. Now, existing keys are checked and emitted on a timer after the subscription is active to prevent gaps.
- **Bug Fixes**
- Moved the check for existing keys to run periodically after subscription setup.
- Ensured no events are missed if they occur between the initial check and subscription start.
> fix task race

- go.mod
- go.sum
Updated geesefs and s3ext dependencies to fix a panic issue. This ensures more stable file system operations.
> fix geesefs panic

- pkg/api/v1/task.go
Restored the correct task serialization in the RetrieveTask API endpoint to fix response formatting.
> Fix: revert code that was incorrectly reverted

- sdk/src/beta9/abstractions/function.py
Improved handling of Ctrl-C during mapped function execution to ensure clean shutdown and better user feedback.
- **Bug Fixes**
- Cancels running tasks and exits cleanly when Ctrl-C is pressed.
- Shows clear error messages if tasks fail or are interrupted.
> handle ctrl-c correctly during mapped function

- sdk/src/beta9/abstractions/endpoint.py
Docs say 3600 seconds (1 hour) but it's actually 180 seconds (3 minutes)
> Fix docs: Default endpoint timeout is 180, not 3600

- pkg/abstractions/volume/volume.go
- sdk/src/beta9/cli/volume.py
1. Made volume ls return value consistent for workspace and non-workspace storage
2. Show only final path in the volume ls command (so it doesnt render entire object path when inspecting a dir)
> Fix: Patch volume pathing

- pkg/abstractions/shell/shell.go
```
if !strings.Contains(event.Key, Keys.shellContainerTTL("")) {
containerId := shellContainerPrefix + event.Key
if ss.rdb.Exists(ss.ctx, Keys.shellContainerTTL(containerId)).Val() == 0 {
ss.scheduler.Stop(&types.StopContainerArgs{
ContainerId: containerId,
Force:       true,
Reason:      types.StopContainerReasonTtl,
})
}
}
```
If this key doesn't exist the container is sent a stop event.
Initially this was set too low. The expectation was that the keepalive would refresh it. However, the keepalive requires the ssh server to be active which wont always happen for images that take too long to spin up.
This extends the initial keepalive of this key to the same duration as the waitForContainer check
> Fix: Increase initial wait time of shell
