beam-cloud/beta9

pkg/abstractions/image/build.go, pkg/abstractions/image/image.go, sdk/pyproject.toml, sdk/src/beta9/abstractions/image.py
- Fix requirements.txt parsing
- Fix base image error handling
- Sanitize input python_packages format 
- Ensure build output is formatted properly
- Ensure image ID matches during verify/build (this was only an issue in custom base image builds)
=> Image build fixes

docker/Dockerfile.worker
- Temporarily remove mountpoint
- Upgrade fuse
=> Upgrade fuse to fuse3 in Worker

go.mod, go.sum, pkg/common/aws.go, pkg/common/config.default.yaml, pkg/common/registry.go, pkg/providers/ec2.go, pkg/types/config.go, pkg/worker/image.go
- Allows images to be stored in external s3 compatible storage
- Modifies s3 config type to be more generic
=> Add support for non-aws s3 compatible storage

pkg/scheduler/pool_external.go, pkg/scheduler/pool_local.go, sdk/src/beta9/__init__.py
- Always pull an image when the tag is "latest"
- Pull if not present when tag is anything else (default)
=> Add pullpolicy when scheduling new workers

pkg/auth/http_test.go
Small test case for the WithClusterAdminAuth auth wrapper
=> Commit test for WithClusterAdminAuth

sdk/pyproject.toml, sdk/src/beta9/abstractions/output.py, sdk/src/beta9/channel.py, sdk/src/beta9/runner/common.py, sdk/src/beta9/runner/state.py
- Replace thread local with environment variable
- Use relative import beta9/channel.py
=> Fix passing task id to Output when using beam-client

pkg/common/config.default.yaml, pkg/storage/juicefs.go, pkg/types/config.go
- expose buffer size
- expose prefetch worker counter
=> Expose more juicefs options

go.mod, go.sum, sdk/pyproject.toml, sdk/src/beta9/abstractions/endpoint.py, sdk/src/beta9/abstractions/function.py, sdk/src/beta9/abstractions/taskqueue.py, sdk/src/beta9/runner/endpoint.py
- Default to shutting down the serve container if a user ctrl+c's twice when exiting a serve session
- Handle function serve NotImplementError gracefully
=> Various serve fixes

.github/workflows/release-runner.yml
=> Re-add Python 3.12 to build pipeline

pkg/abstractions/image/base_requirements.txt
=> Add missing package to base requirements

Makefile, proto/gen.sh, sdk/src/beta9/cli/volume.py
- Install python dependencies before generating proto files
- Run proto generation in poetry python env
=> Run proto generation in poetry python env

deploy/charts/beta9/templates/_helpers.tpl
- Should hopefully fix tailscale in gateway
=> Enable host network for gateway

sdk/src/beta9/abstractions/base/runner.py, sdk/src/beta9/abstractions/endpoint.py, sdk/src/beta9/abstractions/taskqueue.py
This fixes serves by having it run synchronously.
=> Fix serve command

README.md, docs/jp/README.md
I created Japanese translated README.
=> docs: add Japanese documentation

go.mod, go.sum
- Expose upload error message and separate upload speed from archive speed
=> Worker: Add more clip logs

sdk/pyproject.toml, sdk/src/beta9/abstractions/base/__init__.py, sdk/src/beta9/abstractions/base/runner.py, sdk/src/beta9/channel.py, sdk/src/beta9/runner/taskqueue.py
- Remove channel closure in base abstraction to prevent premature channel cleanup
- Make monitor task synchronous
=> Worker bugfixes

sdk/pyproject.toml, sdk/src/beta9/abstractions/endpoint.py, sdk/src/beta9/abstractions/taskqueue.py, sdk/src/beta9/runner/endpoint.py
- Fix taskqueue / endpoint serve ctrl+x
- Don't use with_runner_context decorator in endpoints
=> Fix serve ctrl+c

pkg/abstractions/endpoint/buffer.go, pkg/abstractions/endpoint/http.go, sdk/pyproject.toml, sdk/src/beta9/runner/common.py, sdk/src/beta9/runner/endpoint.py
- Stream http responses
- Permit async functions for endpoints
- Add GET method to endpoint http handlers
For example:
=> Add streaming support to endpoints

pkg/gateway/services/machine.go, pkg/providers/base.go, pkg/providers/ec2.go, pkg/providers/lambdalabs.go, pkg/providers/oci.go, pkg/providers/provider.go, pkg/repository/base.go, pkg/repository/provider_redis.go, pkg/scheduler/pool_external.go, pkg/types/provider.go
- Leverage agent in external providers so we don't have to rewrite bootstrapping logic for each provider
- Refactor user data config
- Fix worker machine scheduling issue with small workers
- Add last worker seen to machine to state so we can see the last time a worker was running on a particular machine
- Add auto consolidation of empty machines after 10 min
- Fix panic in lambda labs list func
=> External Provider improvements

pkg/abstractions/common/ring_buffer.go, pkg/abstractions/endpoint/buffer.go, pkg/abstractions/endpoint/endpoint.go, pkg/abstractions/taskqueue/taskqueue.go, pkg/scheduler/scheduler.go, pkg/task/serialize.go
- Fix memory leak in ring buffer
- Fix context cleanup in endpoint instance
- Improve request serialization logic
- Clean up container state for cancelled container requests after 3 attempts at scheduling
=> Fix issues with endpoint abstraction

.stignore, deploy/aws-dev/README.md, deploy/crusoe/README.md
- Update READMEs for terraform deployments
- Ignore more directories in Okteto
Resolve BE-1445
=> Update READMEs for Terraform deployments

.github/workflows/release-cli.yml
=> Update release-cli action workflow

go.mod, go.sum, pkg/gateway/services/machine.go
- Make machine token re-usable
- update blobcache-v2
=> Make agent machine token re-usable and update blobcache

pkg/types/provider.go
- Increase default worker state keepalive to 5 minutes
=> Update worker keepalive ttl

sdk/src/beta9/abstractions/output.py
=> Add directory and PIL.Image support to Outputs

pkg/providers/remote_config.go
- Resolve hostnames through tailscale local client directly instead of through redis lookups
=> Switch from redis to tailscale operator

hack/okteto.yaml, pkg/abstractions/image/build.go, pkg/common/runc_client.go, sdk/src/beta9/terminal.py
=> Fix upload progress when building images

pkg/worker/worker.go
- Force kill stuck containers after TerminationGracePeriod seconds
=> Add sigkill to worker after termination grace period

pkg/abstractions/endpoint/endpoint.go, pkg/abstractions/taskqueue/http.go, pkg/abstractions/taskqueue/taskqueue.go, pkg/types/task.go
Limit task queues / endpoints with max_pending_tasks value.
=> Utilize max_pending_tasks

pkg/common/keys.go, pkg/repository/base.go, pkg/repository/container_redis.go, pkg/repository/worker_redis.go, pkg/worker/worker.go
- Allows tracking of containers by worker ID
=> Track containers by worker id

sdk/pyproject.toml, sdk/src/beta9/abstractions/base/__init__.py
=> Add realtime host to Beam SDK settings

pkg/repository/provider_redis.go
HOTFIX: correct metrics TTL key
=> Fix metrics ttl

pkg/api/v1/container.go
=> Add get container endpoint

pkg/api/v1/task.go, pkg/repository/backend_postgres.go, pkg/types/backend.go
=> Sanitize stub config for task endpoint

pkg/api/v1/task.go
=> Sanitize list tasks endpoint

sdk/src/beta9/abstractions/base/runner.py, sdk/src/beta9/type.py
=> Fix autoscaler validation

go.mod, go.sum, pkg/providers/remote_config.go, pkg/scheduler/pool.go, pkg/scheduler/pool_external.go, pkg/worker/image.go
- Add blobfs cache path to worker
- Integrate into images client
=> Blobfs integration into worker

pkg/worker/image.go
- Check if blobfs (blobcache) cache path is available before trying to look for content there
=> Check if blobfs cache path is available

sdk/pyproject.toml, sdk/src/beta9/abstractions/base/runner.py
- Prevent rich from handling text wrapping
- Add color when printing invocation details
Resolve BE-1517
=> Fix printing invocation details

sdk/pyproject.toml, sdk/src/beta9/type.py
=> Fix Autoscaler class instantiation

pkg/providers/remote_config.go, pkg/types/config.go, pkg/worker/image.go, pkg/worker/worker.go
Since we will also be using Blobcache for things outside of images, this PR moves the config up to the top level.
=> Move blobcache config up to top of config

pkg/repository/provider_redis.go, sdk/pyproject.toml, sdk/src/beta9/cli/machine.py
- Use free GPUs, not total GPUs when displaying GPUs available
- Sort GPUs in table/json view for consistency (backend does not have ordered maps)
- Add shebang to agent bootstrap script for better copy/paste into userdata of provider
- Prevent python-rich from cropping/"correcting" lines in agent bootstrap script for reliable copy/paste
Resolve BE-1542
=> List machine improvements

go.mod, go.sum, manifests/kustomize/components/monitoring/.fluent-bit.env, manifests/kustomize/components/monitoring/elasticsearch.yaml, manifests/kustomize/components/monitoring/fluent-bit.yaml, manifests/kustomize/components/monitoring/kustomization.yaml, pkg/common/config.default.yaml, pkg/repository/base.go, pkg/repository/events.go, pkg/types/config.go, pkg/types/event.go, pkg/worker/events.go, pkg/worker/procutil.go, pkg/worker/worker.go
- Send container metrics to event repo (cpu, mem, gpu, and io)
- Add Elasticsearch to cluster-dev kustomize deployment
Resolve BE-1547
=> Collect and store container metrics from worker

pkg/api/v1/task.go, pkg/repository/backend_postgres.go, pkg/repository/base.go
=> Get tasks by workspace

deploy/charts/beta9/templates/pdb.yaml, deploy/charts/beta9/values.yaml
=> Add pod disruption budget capability

pkg/api/v1/task.go, pkg/gateway/gateway.go, pkg/types/backend.go
=> Add active containers stat to task endpoint

pkg/api/v1/stub.go
=> Get stub as workspace user

docker/Dockerfile.gateway, sdk/pyproject.toml, sdk/src/beta9/sync.py, sdk/src/beta9/terminal.py
- Add progress bar when syncing files
- Fix Dockerfile syntax (latest version Docker complains about this)
Resolve BE-1608
=> Add progress bar when syncing files

go.mod, go.sum
- Updates clip to avoid re-using a state file handle
=> Fix image build caching issue

sdk/pyproject.toml, sdk/src/beta9/abstractions/output.py
- Stat the correct path name when the output is a directory (zipped file)
Resolve BE-1579
=> Fix Output stat function for dir outputs

.gitignore, sdk/pyproject.toml, sdk/src/beta9/abstractions/container.py, sdk/src/beta9/abstractions/endpoint.py, sdk/src/beta9/abstractions/function.py, sdk/src/beta9/abstractions/mixins.py, sdk/src/beta9/abstractions/taskqueue.py, sdk/src/beta9/cli/deployment.py, sdk/src/beta9/type.py
- Fix context not being passed when running `beta9 deploy <fqfn> --name <name> --context <my-context>`
- Fix gpu literal types by using hyphens instead of underscores
- Add a Deployable mixin class for endpoint, function, and taskqueue to use
- Update various docstrings
=> SDK housekeeping

go.mod, go.sum
- Add additional logging to discovered hosts
=> Update blobcache client

pkg/common/keys.go, pkg/repository/base.go, pkg/repository/task_redis.go, pkg/task/dispatch.go, sdk/src/beta9/runner/taskqueue.py
- Prevent multiple replicas from retrying the same tasks
=> Add task retry lock

manifests/kustomize/components/postgresql/helm-chart-generator.yaml
=> Fix pg init script

pkg/worker/nvidia.go, pkg/worker/nvidia_test.go
Lots of packages require this to be set
=> Add cuda_home to container env vars

pkg/scheduler/pool_external.go, pkg/scheduler/pool_local.go, pkg/worker/network.go
- Use existence of KUBE-FORWARD chain to determine host iptables mode
=> Change approach of determining iptables mode

pkg/worker/network.go
- Insert bridge/default interface routing rules towards top of chain
- Change other inserts to insert uniques to prevent duplicate rules
=> Insert foward rules at top of chain

docker/Dockerfile.gateway, docker/Dockerfile.worker, pkg/storage/cunofs.go, pkg/storage/storage.go, pkg/types/config.go
- Add a new storage option (cunofs)
- NOTE: only supported currently on x86
=> Add CunoFS support

pkg/api/v1/machine.go, pkg/repository/base.go, pkg/repository/provider_redis.go, pkg/types/gpu.go
This PR adds an endpoint that returns the platform's GPU count.
=> gpu count endpoint

sdk/src/beta9/terminal.py
Small tweak to make secrets visible in light mode.
=> change color of shown secrets so they are visible in light mode

pkg/api/v1/task.go
Currently we use the workspace name from the auth context. With requests coming from internal-api that will be the name of the admin workspace and not necessarily the user's workspace name. This change retrieves the correct workspace name no matter where the request originates from.
=> Use the user's workspace name when adding task stats

sdk/pyproject.toml, sdk/src/beta9/abstractions/base/__init__.py
=> Use defaults in prompt for beam sdk settings

pkg/gateway/services/stub.go
=> Stop previous deployment on new scheduled jobs deployment

sdk/src/beta9/abstractions/base/runner.py
This PR adds support for calling remote functions inside of jupyter notebooks.
=> Jupyter remote functions

pkg/repository/backend_postgres.go, pkg/types/backend.go
Fixes bug where tasks don't appear under serves
=> left join task with related

docker/Dockerfile.runner
=> Update urllib3 to fix tls issues with requests

sdk/src/beta9/runner/common.py, sdk/src/beta9/runner/function.py, sdk/src/beta9/runner/taskqueue.py
It looks like a log of changes but all im really doing is wrapping the logic around a try-finally block where in the finally block, I shut down the thread pool executor
=> Shutdown threadpool executor when function errors

pkg/common/config.default.yaml, pkg/types/config.go
Removes unused baseImageTag field.
=> Remove config key

sdk/src/beta9/abstractions/base/__init__.py, sdk/src/beta9/runner/endpoint.py
=> Fix Outputs in ASGI endpoints

bin/delete_workers.sh, deploy/aws-dev/modules/k8s-resources/config.tpl, go.mod, go.sum, pkg/abstractions/container/container.go, pkg/abstractions/endpoint/instance.go, pkg/abstractions/function/task.go, pkg/abstractions/image/build.go, pkg/abstractions/taskqueue/instance.go, pkg/common/config.default.yaml, pkg/providers/remote_config.go, pkg/repository/backend_postgres.go, pkg/repository/backend_postgres_migrations/013_add_workspace_volume_cache.go, pkg/types/backend.go, pkg/types/config.go, pkg/types/scheduler.go, pkg/worker/file_cache.go, pkg/worker/image.go, pkg/worker/worker.go, sdk/src/beta9/runner/common.py, sdk/src/beta9/runner/serve.py
- Enables caching of volume contents via intercept of open calls
- Refactors blobcache config to be more consistent across images / mount contents
- Disable volume caching by default
=> File caching system

sdk/pyproject.toml, sdk/src/beta9/cli/deployment.py
=> Show path-based URL when creating deployments

pkg/auth/http.go
No one is using websockets at the moment so I will change the URL param key for this
=> Change url param to look for in auth

pkg/repository/backend_postgres_migrations/016_subdomains.go
=> Lower subdomain column in migration

pkg/abstractions/endpoint/buffer.go
Fixes sending headers, form data (files), etc.
Resolve BE-1895
=> Send request headers to runner server

sdk/pyproject.toml, sdk/src/beta9/abstractions/image.py, sdk/src/beta9/type.py
=> Add annotation support for python_version strings

pkg/common/events.go
=> Fix: nil dereference error in eventbus

pkg/common/config.default.yaml, pkg/scheduler/pool_local.go, pkg/types/config.go, pkg/worker/worker.go
=> Add config for RunC resource limits

pkg/gateway/services/worker.go
=> Fix: Checking for correct token on worker management endpoints

pkg/abstractions/volume/http.go
Resolve BE-1945
At the moment, if you upload a file via the UI it will likely end up corrupted because the final chunk is not written. 
Here is a quick way to reproduce it. Below I upload 105K zip and only 90.59K actually makes it. Upon downloading the zip, it cannot be opened.
```bash
~/Downloads ❯ ls -lh example.zip
-rw-r--r--@ 1 minzi  staff   105K Sep 25 13:19 example.zip
~/Downloads ❯ curl -X PUT 'http://localhost:1994/volume/951bf68b-29da-4066-9440-a4cc4ea131c4/upload/test/example.zip' \
-H 'Connection: keep-alive' \
-H 'Authorization: Bearer y6ranIRfAb01QsyhpZl4jZru3e-Q0lpIMf0UTC5S2lXsVf46UuRtJ6XJLyRejfn6ToyIc8vOQvwvYOfgUMGnuQ==' \
-H 'Content-Type: application/octet-stream' \
--data-binary '@example.zip'
null
~/Downloads ❯ beta9 ls test
Name                            Size …
```
=> Fix: Ensure complete file uploads over HTTP

pkg/abstractions/common/instance.go, pkg/abstractions/endpoint/autoscaler.go
- Add a couple more traces in autoscaler and instance
=> Add traces in autoscaler

sdk/pyproject.toml, sdk/src/beta9/channel.py
=> Feat: User friendly messaging when payloads/arguments are too big

pkg/scheduler/pool_external.go
=> Set worker version in external pools

sdk/pyproject.toml, sdk/src/beta9/cli/volume.py
=> Show more path when uploading files

hack/okteto.yaml, pkg/abstractions/container/container.go, pkg/abstractions/endpoint/instance.go, pkg/abstractions/function/task.go, pkg/abstractions/taskqueue/instance.go, pkg/scheduler/scheduler.go, pkg/types/scheduler.go
Small changes relating to cleanup and adding of a helper function for validating gpu requirements.
Also moved `container.scheduled` events after request.Gpu is updated
=> Chore: Cleanup logic for gpu count and added a helper to check GPU requirements

sdk/pyproject.toml, sdk/src/beta9/cli/config.py
=> Feat: Display config path after adding new context to config

sdk/pyproject.toml
Bumped sdk version for publish
=> publish 0.1.101 sdk w/ vllm

sdk/pyproject.toml, sdk/src/beta9/abstractions/integrations/vllm.py
This change fixes the default mounted volume and sets a default download directory for vLLM.
=> Better default caching behavior for vLLM

sdk/pyproject.toml, sdk/src/beta9/abstractions/integrations/vllm.py
=> Remove tuple in vllm args class

sdk/pyproject.toml, sdk/src/beta9/abstractions/base/runner.py
Errors on missing attribute for non-realtime deployments right now
=> set default on runner for websocket flag

pkg/abstractions/experimental/bot/instance.go, sdk/src/beta9/abstractions/experimental/bot/bot.py
- don't fire transitions with no inputs
- validate inputs dicts
=> Fix: fix a couple agent bugs

bin/delete_workers.sh, cmd/worker/main.go, pkg/worker/worker.go
=> Fix: On worker shutdown, handle worker not found error

pkg/abstractions/experimental/bot/state.go, pkg/abstractions/experimental/bot/types.go, sdk/pyproject.toml, sdk/src/beta9/abstractions/experimental/bot/bot.py, sdk/src/beta9/abstractions/experimental/bot/types.py
- Add created_at to bot session struct
- Add send_file helper to bot context
- Add OUTPUT_MESSAGE event
=> Feat: Bot session updates

pkg/abstractions/image/credentials.go, pkg/abstractions/image/credentials_test.go, sdk/src/beta9/abstractions/image.py
- Add ability to use docker hub credentials to pull private images
- Improve typing for image credentials
Resolve BE-2061
=> Feat: Add docker hub support for private images

pkg/abstractions/image/credentials.go, pkg/abstractions/image/credentials_test.go, sdk/src/beta9/abstractions/image.py
- Add ability to use google access tokens to pull private images from GAR
- Update Image class docstring
Resolve BE-2059
=> Feat: Add Google Artifact Registry support for private images

pkg/abstractions/image/credentials.go, pkg/abstractions/image/credentials_test.go, sdk/src/beta9/abstractions/image.py
=> Feat: Add NVIDIA GPU Cloud support for private images

pkg/abstractions/experimental/bot/bot.go, pkg/abstractions/experimental/bot/instance.go, pkg/abstractions/experimental/bot/state.go, pkg/abstractions/experimental/bot/types.go
- Adds full event history to bot session response object
=> Bot: Add event history to bot session response

go.mod, go.sum
- makes discovery use metadata instead of tailscale
=> Update blobcache discovery

pkg/common/config.default.yaml, pkg/scheduler/pool_external.go, pkg/scheduler/pool_local.go, pkg/types/config.go, pkg/worker/cr.go, pkg/worker/lifecycle.go, pkg/worker/worker.go
=> feat: configure criu per worker pool

pkg/abstractions/image/build.go, pkg/abstractions/image/build_test.go
Instead of flushing on every flag, flush on flags that will impact the installs of other libraries.
=> More specific flags to flush on

sdk/pyproject.toml, sdk/src/beta9/abstractions/integrations/vllm.py
This adds a few more missing args from the latest vllm version
=> Add missing vllm args for vllm v0.6.4.post1

pkg/scheduler/pool_manager.go, pkg/scheduler/pool_manager_test.go
=> feat: sort gpu controllers by priority

sdk/pyproject.toml, sdk/src/beta9/abstractions/output.py
=> feat: support saving empty files with outputs

pkg/types/config.go
Adds config for victoria logs.
=> Add vm logs config

pkg/abstractions/endpoint/buffer.go, pkg/abstractions/endpoint/endpoint.go, pkg/abstractions/endpoint/task.go
There may be a possible race condition here since the timing of the expiry and the interval are so close together.
=> Fix: increase heartbeat frequency

sdk/src/beta9/runner/function.py
- Under cpu bound workloads, threads can become unresponsive, and not actually run. This moves monitor_task to a separate process and avoids the GIL
=> Fix: move function monitor to process

pkg/abstractions/image/build.go, pkg/abstractions/image/image.go, pkg/common/key_events.go, pkg/gateway/gateway.go
This reverts commit b5f5bb7c7fe4a44753488d60cc1ff0867fc071f3.
=> Revert "Fix: Add a TTL on build containers for cleanup (#819)"

sdk/pyproject.toml, sdk/src/beta9/multipart.py
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
Resolve BE-2133
=> fix: type error with progress updater

sdk/pyproject.toml, sdk/src/beta9/multipart.py, sdk/src/beta9/terminal.py
- When uploading/downloading a directory, glob all directories and files
- Fix AverageTransferSpeedColumn so it renders per task, not for all tasks
Resolve BE-2133
=> feat: multipart upload/download directories recursively

pkg/abstractions/volume/multipart.go
=> fix: panic makeslice len out of range

sdk/src/beta9/env.py
This PR adds an additional notebook check for [hex](https://hex.tech/) notebooks. They have an included an `in_notebook` method for us to leverage.
=> Feat: Functions can be invoked in Hex notebooks

pkg/abstractions/image/build.go, pkg/abstractions/image/build_test.go, pkg/scheduler/pool.go, pkg/scheduler/pool_external.go, pkg/scheduler/pool_local.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
- fix bug with pip flag
- fix pool selector flag in scheduler
=> fix: pass root user action as env var instead of flag

docker/Dockerfile.worker
=> Update container toolkit to 1.17.3

sdk/pyproject.toml, sdk/src/beta9/abstractions/shell.py
=> fix: add backoff when waiting for socket connection

pkg/worker/lifecycle.go
Resolve BE-2284
Build containers always fail to read `initial_config.json` at the bundle path of the base image because it does not exist. Given that its a base image, the actual config location is `config.json`. Therefore, I check the nature of the container request and then read the correct location. I also added additional logging. 
Unsloth still doesn't build correctly :(
=> Fix: Build container's should have base image env vars 

sdk/pyproject.toml, sdk/src/beta9/cli/worker.py
I plan on using this to cycle the A10s
=> Feat: Drain & cordon by machine id

pkg/abstractions/taskqueue/taskqueue.go, sdk/src/beta9/runner/taskqueue.py
=> fix: ensure task monitor in taskqueue functions properly during rollout restart

pkg/worker/worker.go
This can sometimes prevent spin down of the worker if a StoreContentFromSource call was taking a while in the background.
=> fix: use worker ctx in cache client

bin/setup.sh, cmd/worker/main.go
- worker - Log err when worker fails to start
- setup.sh - Detect aarch64 when on Linux
=> feat: log err when worker fails to start

sdk/pyproject.toml, sdk/src/beta9/abstractions/function.py
=> fix: display correct local timezone on deploy

pkg/worker/lifecycle.go, pkg/worker/nvidia.go, pkg/worker/nvidia_test.go
https://github.com/beam-cloud/beta9/pull/905
This does not seem to be the source of the gpu workload failures.
=> Merge env paths

pkg/repository/base.go, pkg/repository/events.go, pkg/scheduler/pool_health.go, pkg/scheduler/pool_sizing.go, pkg/types/event.go
- improve messaging / events
- make sure we don't spam logs unless state changes
=> fix: failover pool fixes

pkg/common/config.default.yaml, pkg/repository/base.go, pkg/repository/events.go, pkg/repository/testutils.go, pkg/repository/worker_redis.go, pkg/scheduler/pool.go, pkg/scheduler/pool_external.go, pkg/scheduler/pool_local.go, pkg/types/config.go, pkg/types/event.go
- Cleanup workers on external worker pools
- Delete k8s worker jobs when worker state no longer exists
- Rename worker cleanup config keys
- Move cleanup interval to config
Resolve BE-2343
=> feat: cleanup workers in external pools

pkg/storage/juicefs.go
Forgot to remove the Start(). CombinedOutput() starts the command too.
=> fix: remove extra juicefs start command

pkg/abstractions/endpoint/buffer.go
Not entirely sure we need this channel, but previously when I tested only with the request context I had some weird issues. Anyway, if we're using the the channel we should at least use it correctly.
=> fix: properly close endpoint buffer channel

pkg/abstractions/common/mount.go, pkg/abstractions/endpoint/serve.go, pkg/abstractions/taskqueue/serve.go, pkg/gateway/services/container.go
- Allow volume mounts to be mounted to root paths (i.e. /my-volume)
=> fix: hotfix to allow absolute mounts

pkg/abstractions/image/build.go, pkg/common/config.default.yaml, pkg/types/config.go
=> feat: use default docker creds if they are configured

pkg/worker/lifecycle.go
=> Loading image log

pkg/worker/lifecycle.go
Right now, the retries often happen too quickly. This change gives the OOM watcher a better chance of success.
=> Exponential backoff for oom channel

pkg/abstractions/volume/http.go
Followup: Test and apply HTML encoding on uploaded files
=> Bug: Download files as attachments to help prevent XSS

go.mod, go.sum
- Ensures reads are null terminated if less < buffer size
=> Fix: ensure dest buffers are null terminated

pkg/api/v1/machine.go, pkg/gateway/gateway.go, pkg/gateway/services/machine.go, pkg/gateway/services/stub.go, pkg/repository/base.go, pkg/repository/worker_redis.go, pkg/scheduler/utils.go, pkg/scheduler/utils_test.go, pkg/types/backend.go, pkg/types/gpu.go
Below T4 is local spot and A10g is remote lambda node.
=> Fix: any should not fail for serve

pkg/worker/runc_resources.go
Instead of hard limits on cpu, modify to use cpu shares instead.
=> fix: remove hard cpu limits

pkg/api/v1/machine.go, pkg/repository/base.go, pkg/repository/provider_redis.go, pkg/scheduler/pool_external.go
* remove setmachinestatusready 
* set machine status to ready during keepalive
* add condition to status check during scheduling to support migration
=> Set machine status to ready during keepalive

pkg/scheduler/pool_external.go
Fixed a potential nil pointer dereference in the worker pool controller. This change adds a safety check to skip nil workers during the worker addition process.
**Bug Fixes**
- Added a nil check for workers in the AddWorker function to prevent crashes
- Ensures the controller gracefully continues to the next worker when encountering nil values
=> fix nil worker issue

docker/Dockerfile.worker, pkg/scheduler/pool_external.go, pkg/scheduler/pool_local.go
Set the BLOBCACHE_LOCALITY environment variable for workers to ensure correct cache locality handling.
=> fix: fix blobcache locality on workers

pkg/worker/usage.go
// If there's a non-AI description already, add a separator
Added calculation and reporting of the actual container cost for the elapsed duration.
- **New Features**
- Now tracks and emits the total cost for each container based on its runtime.
=> Add actual cost for elapsed duration

go.mod, go.sum
Updated blobcache-v2 dependency to the latest version. This brings in the newest fixes and improvements from blobcache.
=> fix: bump blobcache

pkg/api/v1/deployment.go, pkg/repository/backend_postgres.go, pkg/repository/base.go
Resolve BE-2527
This query is currently incorrect
---
Fixed the workspace storage query to correctly join the workspace and workspace_storage tables when fetching storage details.
=> fix workspace storage query

go.mod, go.sum
Updated the github.com/beam-cloud/clip dependency to the latest version.
=> fix: bump clip

pkg/clients/storage.go, pkg/gateway/services/object.go, pkg/registry/registry.go, pkg/storage/geese.go, pkg/worker/mount.go
Improved object existence checks and optimized container loading when using workspace storage.
- **Performance**
- Added faster object existence checks using a lightweight S3 request.
- Updated container mount logic to better handle workspace storage.
- Enabled directory preload optimizations for GeeseFS mounts.
=> improve object lookup, and container load w/ workspace storage

pkg/repository/backend_postgres_migrations/026_add_app_table.go
Simplified the app migration script by creating a single default app per workspace and updating related stub and deployment records.
- **Refactors**
- Removed complex logic for mapping stubs and deployments to apps.
- Now assigns all stubs and deployments in a workspace to the default app.
=> Update migration script for apps

sdk/pyproject.toml, sdk/src/beta9/abstractions/base/runner.py, sdk/src/beta9/abstractions/endpoint.py, sdk/src/beta9/abstractions/function.py, sdk/src/beta9/abstractions/pod.py, sdk/src/beta9/abstractions/taskqueue.py
Updated how the app name is set in the runner. The app name now defaults to the runner name or current directory only if not provided.
=> update app name

go.mod, go.sum, pkg/worker/image.go
Updated the blobcache-v2 dependency to the latest version to fix cache issues.
=> fix cache dep

pkg/types/config.go
Added a new k3sInstallDir field to WorkerPoolConfig to specify the K3s installation directory.
=> add k3s install dir

deploy/charts/beta9/Chart.lock, deploy/charts/beta9/Chart.yaml
Fixed the Helm chart deployment by updating the repository URL for the common dependency.
=> fix: fix chart deploy

pkg/api/v1/machine.go
Updated the machine config API to return the config inside a "config" field in the JSON response.
=> fix config

pkg/types/backend.go
Added the workspace signing key to the serializer so it is included in serialized workspace data.
=> Serialize signing key of workspace

go.mod, go.sum
Updated geesefs and s3ext dependencies to the latest versions for improved compatibility and bug fixes.
=> bump geesefs again

bin/setup.sh
=> dont use -u flag in setup

go.mod, go.sum, pkg/common/config.default.yaml, pkg/storage/geese.go, pkg/types/config.go, pkg/worker/storage_manager.go
=> feat: integrate optional cache streaming

docker/Dockerfile.runner
=> Fix pip installation for python3.8

pkg/abstractions/shell/shell.go
This is a simple change but I might want to hold off to clean up and configure everything into a config https://openwrt.org/docs/guide-user/base-system/dropbear
=> Fix: Add /usr/local/bin to path
